//! Smoke test for the OpenAPI document generated by `calm_server::openapi`.
//!
//! Asserts every route we annotated is present in `paths`, every component
//! schema is present in `components.schemas`, and the JSON serialization
//! round-trips cleanly. The frontend toolchain consumes this exact JSON via
//! `GET /api/openapi.json`, so a missing schema here is a wire-types
//! contract violation.

use calm_server::openapi::ApiDoc;
use utoipa::OpenApi;

#[test]
fn document_contains_every_annotated_path() {
    let doc = ApiDoc::openapi();
    let expected_paths = [
        "/api/coves",
        "/api/coves/{id}",
        "/api/coves/{cove_id}/waves",
        "/api/waves",
        "/api/waves/{id}",
        "/api/waves/{wave_id}/cards",
        "/api/cards/{id}",
        "/api/cards/{card_id}/terminal",
        "/api/waves/{wave_id}/terminal-cards",
        "/api/overlays",
        "/api/overlays/delete",
        "/api/plugins",
        "/api/plugins/views",
        "/api/plugins/install",
        "/api/plugins/{id}",
        "/api/plugins/{id}/enable",
        "/api/plugins/{id}/disable",
        "/api/plugins/{id}/config",
        "/api/plugins/{id}/log",
        "/api/plugins/{id}/reload",
        "/api/plugins/{id}/rotate-token",
        "/api/plugins/{id}/resources/{view_id}",
        "/api/plugins/{id}/tool-call",
    ];
    for path in expected_paths {
        assert!(
            doc.paths.paths.contains_key(path),
            "expected path `{path}` in OpenAPI document; got: {:?}",
            doc.paths.paths.keys().collect::<Vec<_>>()
        );
    }
}

#[test]
fn document_contains_every_wire_model() {
    let doc = ApiDoc::openapi();
    let components = doc
        .components
        .as_ref()
        .expect("components present in OpenAPI document");
    let schemas: Vec<&String> = components.schemas.keys().collect();
    let expected_schemas = [
        // domain models
        "Cove",
        "NewCove",
        "CovePatch",
        "Wave",
        "NewWave",
        "WavePatch",
        "WaveDetail",
        "Card",
        "NewCard",
        "CardPatch",
        "Overlay",
        "NewOverlay",
        "Terminal",
        "Plugin",
        // route-local DTOs
        "CreateCardBody",
        "ViaToolCall",
        "NewTerminalCardBody",
        "OverlayQuery",
        "OverlayDeleteBody",
        "InstallBody",
        "InstallSource",
        "PluginDetail",
        "PluginListItem",
        "ToolCallBody",
        "ViewCatalogEntry",
        "ViewSizeWire",
        // shared error response
        "ErrorBody",
    ];
    for name in expected_schemas {
        assert!(
            schemas.iter().any(|s| s.as_str() == name),
            "expected schema `{name}` in OpenAPI document; got: {:?}",
            schemas
        );
    }
}

#[test]
fn document_serializes_to_json() {
    let doc = ApiDoc::openapi();
    let json = serde_json::to_value(&doc).expect("OpenAPI doc serializes to JSON");
    // Spec must declare itself as OpenAPI 3.x — `openapi` field with a
    // version string is the entry point clients sniff.
    assert!(
        json.get("openapi")
            .and_then(|v| v.as_str())
            .map(|s| s.starts_with("3."))
            .unwrap_or(false),
        "OpenAPI document missing/invalid `openapi` version field: {json}"
    );
    let paths = json
        .get("paths")
        .and_then(|v| v.as_object())
        .expect("paths present");
    assert!(!paths.is_empty(), "paths must not be empty");
    let schemas = json
        .pointer("/components/schemas")
        .and_then(|v| v.as_object())
        .expect("components.schemas present");
    assert!(!schemas.is_empty(), "schemas must not be empty");
}
