// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Semantic identity of an event producer.
 */
export type ActorId = { "kind": "User" } | { "kind": "Kernel" } | { "kind": "KernelDispatcher" } | { "kind": "Plugin", "id": string } | { "kind": "AiPlanner", "id": CardId } | { "kind": "AiCodex", "id": CardId } | { "kind": "AiClaude", "id": CardId } | { "kind": "AiPlannerSession", "id": WorkerSessionId } | { "kind": "AiCodexSession", "id": WorkerSessionId } | { "kind": "AiClaudeSession", "id": WorkerSessionId };

export type AgentProvider = "codex" | "claude";

export type Area = { id: AreaId, name: string, color: string, sort: number, kind: AreaKind, created_at: number, updated_at: number, };

/**
 * One row of `GET /api/areas/{area_id}/conversations` (#1098 §5.5).
 *
 * Deliberately absent:
 * * `trackTitle` — every row belongs to the same hidden area chat track, so
 *   returning its title would leak an object the user is never shown.
 * * `turns` — the server cannot produce a turn count that agrees with the
 *   drawer without re-parsing every `harness_items.params` blob; a number
 *   that silently disagrees is worse than no number.
 */
export type AreaConversationSummary = { 
/**
 * The chat card's id. This is the conversation's identity everywhere.
 */
id: string, trackId: string, 
/**
 * The conversation's own name, or null before it has one. Never the
 * track's title.
 */
title: string | null, 
/**
 * Always `"shared-chat"`, derived from the card's persisted marker rather
 * than from the session kind (the session is an ordinary codex-card
 * session and says nothing about the conversation being an area chat).
 */
kind: string, 
/**
 * The live session's state, or **null when the card has no session row**.
 *
 * This must stay nullable and must never be filled with an invented
 * value. The list is a LEFT JOIN precisely so a card whose session is
 * gone (failed start, superseded runtime, shut-down harness) stays
 * visible; substituting `idle` or `exited` here would report a session
 * state that was never read.
 */
state: WorkerSessionState | null, 
/**
 * The session's last update, falling back to the card's own — a card
 * minted seconds ago with no session yet still sorts sensibly.
 */
updatedAt: number, };

/**
 * One row per claimed directory; `path` is absolute and globally
 * unique across the table. A folder transparently covers every
 * descendant path — the kernel resolves a `cwd` to its owning area by
 * finding the claim that covers it (see `GET /api/areas/resolve`).
 * The create endpoint rejects ancestor/descendant overlap with a 409,
 * so at most one claim can cover any given path.
 */
export type AreaFolder = { id: number, area_id: AreaId, path: string, created_at: number, };

/**
 * Area identifier. UUID-shaped (32 hex, no dashes) in practice, but the
 * kernel treats the value as opaque; never parses it.
 */
export type AreaId = string;

/**
 * Whether an area is user-visible or kernel-owned storage scaffolding.
 */
export type AreaKind = "user" | "system";

/**
 * Issue #250 PR 1 — 200 body for `GET /api/areas/resolve`. The
 * resolve endpoint returns `null` (not 404) on miss; this struct is
 * the `Some(_)` payload.
 */
export type AreaResolve = { area_id: AreaId, folder_id: number, folder_path: string, };

/**
 * Opaque identifier for a worker-produced artifact.
 */
export type ArtifactRef = string;

export type Card = { id: CardId, track_id: TrackId, 
/**
 * `"terminal"` for built-in PTY cards, `"ui://<plugin>/<view>"` for
 * plugin-provided cards (the canonical MCP Apps resource URI). The
 * kernel never interprets beyond that prefix. `[legacy]`
 * `"plugin:<plugin-id>:<view-id>"` may still appear on persisted rows.
 */
kind: string, sort: number, 
/**
 * Opaque JSON blob — ts-rs would otherwise emit `unknown` via the
 * `serde-json-impl` feature, but we pin it explicitly so a future
 * feature-flag change can't silently widen / narrow the surface.
 */
payload: unknown, title?: string, runtime?: CardRuntimeView, 
/**
 * Issue #229 PR A — system-card guard. `true` for user-facing cards
 * (the default; all pre-#229 rows backfill via the column DEFAULT in
 * migration 0013). `false` for kernel-owned cards that the user
 * cannot remove via REST / plugin callbacks — currently planner cards
 * (retroactively undeletable via the same migration's UPDATE) and
 * PR B's track-report cards.
 *
 * `#[serde(default = "default_deletable")]` so wire payloads emitted
 * before #229 landed (event-log replay fixtures, old test seeds)
 * parse as `true` without forcing a fixture rewrite — matches the
 * DB DEFAULT (1) in migration 0013. The default-fn lives below
 * because `bool::default()` would give `false` (the *un*safe
 * fallback for a deny-by-omission auth bit).
 */
deletable: boolean, created_at: number, updated_at: number, };

/**
 * Card identifier. See [`AreaId`] for the opacity contract.
 */
export type CardId = string;

/**
 * Authorization role persisted on each card and enforced by `role_gate`.
 */
export type CardRole = "worker" | "planner" | "reportcard" | "assistant";

/**
 * Live runtime projection read from `worker_sessions` when a card is fetched
 * or serialized.
 *
 * This view is not part of the idempotency contract: across retries the
 * worker session may have advanced, so `Card.runtime` may differ between the
 * first POST response and a retry POST response returning the same operation
 * result. Future cleanup (#581 item 4) will remove the legacy payload-key
 * projection; this typed view is the forward-compatible reader path.
 */
export type CardRuntimeView = { runtime_id: string, kind: WorkerSessionKind, status: WorkerSessionState, provider?: AgentProvider, terminal_id?: string, thread_id?: string, session_id?: string, source?: string, thread_status?: string, };

/**
 * Per-channel verdict recorded on a `review.round`.
 */
export type ChannelVerdict = { role: string, verdict: ChannelVerdictKind, };

export type ChannelVerdictKind = "approved" | "changes_requested";

/**
 * Producer of a track-report edit. Existing variants are persisted wire values.
 */
export type EditAuthor = "planner" | "user" | "assistant" | "kernel" | "plugin";

/**
 * The full set of WS event envelopes the kernel emits on `/api/events`.
 *
 * `ts-rs` derives a matching TypeScript discriminated union, written to
 * `fe/core/api/generated/wire.ts` when `cargo test export_bindings_` runs
 * (driven by `npm run gen:api`). The serde `tag`/`content` attributes are
 * honored — the emitted TS uses the same `{ ev, data }` envelope.
 *
 * Note for future variants: ts-rs requires every payload type referenced
 * here to also derive `TS`. Inline struct variants (e.g. `AreaDeleted { id }`)
 * are emitted directly; tuple variants over a named struct (e.g.
 * `AreaUpdated(Area)`) pull in the struct's own export.
 */
export type Event = { "ev": "area.updated", "data": Area } | { "ev": "area.deleted", "data": { id: AreaId, } } | { "ev": "track.updated", "data": TrackUpdatedPayload } | { "ev": "track.deleted", "data": { id: TrackId, area_id: AreaId, } } | { "ev": "track.lifecycle_changed", "data": { id: TrackId, area_id: AreaId, from: TrackLifecycle, to: TrackLifecycle, agent_message?: string, } } | { "ev": "card.added", "data": Card } | { "ev": "card.updated", "data": Card } | { "ev": "card.deleted", "data": { id: CardId, track_id: TrackId, } } | { "ev": "runtime.started", "data": { runtime_id: string, card_id: string, kind: WorkerSessionKind, agent_provider: AgentProvider | null, status: WorkerSessionState, } } | { "ev": "runtime.status_changed", "data": { runtime_id: string, card_id: string, old_status: WorkerSessionState, new_status: WorkerSessionState, } } | { "ev": "runtime.superseded", "data": { old_runtime_id: string, new_runtime_id: string, card_id: string, } } | { "ev": "harness.item.added", "data": { runtime_id: string, card_id: CardId, track_id: TrackId, item_db_id: number, item_uuid: string | null, item_type: string | null, turn_id: string | null, method: string, } } | { "ev": "harness.phase.changed", "data": { runtime_id: string, card_id: CardId, track_id: TrackId, old_phase: HarnessPhaseTag, new_phase: HarnessPhaseTag, } } | { "ev": "harness.transcript.cleared", "data": { runtime_id: string, card_id: CardId, track_id: TrackId, 
/**
 * Number of `harness_items` rows deleted by this reset.
 * `None` on pre-#1252 rows only.
 */
cleared_item_count: number | null, 
/**
 * Summed byte length of those rows' `params` payloads — the only
 * cumulative-size measure the `harness_items` schema carries
 * (there is no token-count column). `None` on pre-#1252 rows only.
 */
cleared_params_bytes: number | null, 
/**
 * Card age at reset: emit time minus the card row's `created_at`,
 * in milliseconds. Lets a retrospective tell "reset an hour in"
 * from "reset after a week". `None` on pre-#1252 rows only.
 */
card_age_ms_at_clear: number | null, } } | { "ev": "harness.user_message.enqueued", "data": { runtime_id: string, card_id: CardId, track_id: TrackId, char_count: number, } } | { "ev": "track.report_edited", "data": { track_id: TrackId, card_id: CardId, author: EditAuthor, 
/**
 * Submitting plugin id when `author == EditAuthor::Plugin`
 * (#955 §5.3); `None` for every other author.
 * `#[serde(default)]` keeps pre-#955 history rows replayable
 * (field absent on old events ⇒ `None`).
 */
author_plugin_id?: string, edit_id: string, summary_before: string, summary_after: string, body_before: string, body_after: string, agent_message?: string, } } | { "ev": "overlay.set", "data": Overlay } | { "ev": "overlay.deleted", "data": { plugin_id: string, entity_kind: string, entity_id: string, kind: string, } } | { "ev": "terminal.deleted", "data": { id: string, card_id: CardId, } } | { "ev": "plugin.state", "data": { id: string, state: string, 
/**
 * Crash reason / initialize-rejected message, surfaced to the WS so
 * the UI can show it without a separate `/log` fetch. `None` for
 * healthy transitions (Spawning → Running, etc.). Wire shape locked
 * in design doc §7.
 *
 * `#[serde(default, skip_serializing_if = "Option::is_none")]`
 * combined with `#[ts(optional)]` matches the runtime behavior: the
 * field is absent on the wire when the inner `Option` is `None`, and
 * the TS type marks it as `last_error?: string`. (Without `optional`,
 * ts-rs would emit `last_error: string | null` which would diverge
 * from what the server actually serializes.)
 */
last_error?: string, } } | { "ev": "plugin.tool.registered", "data": { plugin_id: string, tool_name: string, } } | { "ev": "codex.hook", "data": { 
/**
 * Owning card id — topic key `card:<card_id>`.
 */
card_id: CardId, 
/**
 * Snake_case discriminator: `hook.codex.<event_name>` (e.g.
 * `hook.codex.pre_tool_use`). Derived from `hook_event_name` in
 * the codex payload; defaults to `hook.codex.unknown` if missing.
 */
kind: string, 
/**
 * Stable hook ingest key used by the server and planner harness to
 * suppress duplicate lifecycle posts.
 */
hook_idempotency_key: string, 
/**
 * Original codex hook JSON, verbatim.
 */
payload: unknown, } } | { "ev": "claude.hook", "data": { 
/**
 * Owning card id — topic key `card:<card_id>`.
 */
card_id: CardId, 
/**
 * Hook discriminator supplied by the future Claude hook route.
 */
kind: string, 
/**
 * Stable hook ingest key used by the server and planner harness to
 * suppress duplicate lifecycle posts.
 */
hook_idempotency_key: string, 
/**
 * Original Claude hook JSON, verbatim.
 */
payload: unknown, } } | { "ev": "codex.worker_requested", "data": { idempotency_key: string, goal: string, context: unknown, acceptance_criteria?: string, agent_message?: string, } } | { "ev": "terminal.worker_requested", "data": { idempotency_key: string, cmd: string, cwd?: string, agent_message?: string, } } | { "ev": "task.completed", "data": { idempotency_key: string, result: unknown, artifacts: Array<ArtifactRef>, agent_message?: string, } } | { "ev": "task.failed", "data": { idempotency_key: string, reason: string, agent_message?: string, } } | { "ev": "plan.updated", "data": { track_id: TrackId, changed_keys: Array<string>, agent_message?: string, } } | { "ev": "task.dispatched", "data": { idempotency_key: string, kind: string, agent_message?: string, } } | { "ev": "task.context_frozen", "data": { track_id: TrackId, task_key: string, idempotency_key: string, task_id: string, refs: Array<TaskContextRef>, doc_revs: { [key in string]: number }, truncated: boolean, } } | { "ev": "task.context_advanced", "data": { track_id: TrackId, task_key: string, task_id: string, changed_refs: Array<TaskContextChangedRef>, verdict: string, rationale: string, } } | { "ev": "workspace.leased", "data": { track_id: TrackId, card_id: CardId, lease_id: string, path: string, } } | { "ev": "workspace.released", "data": { track_id: TrackId, card_id: CardId, lease_id: string, } } | { "ev": "forge.pr.merged", "data": { track_id: TrackId, subject: ForgeMergeSubject, head_sha: string, merge_sha: string, } } | { "ev": "review.round", "data": { track_id: TrackId, subject: ReviewSubject, head_sha: string | null, n: number, cap: number, converged: boolean, channels: Array<ChannelVerdict>, root_cause: string | null, idempotency_key: string, } } | { "ev": "ratify.requested", "data": { track_id: TrackId, reason: string, } } | { "ev": "ratify.resolved", "data": { track_id: TrackId, decision: RatifyDecision, } } | { "ev": "proposal.submitted", "data": { track_id: TrackId, proposal_id: string, 
/**
 * Submitting plugin. Injected kernel-side from the callback
 * connection (never trusted from plugin input) and
 * cross-checked against the envelope actor by `role_gate`.
 */
plugin_id: string, 
/**
 * Proposal subject kind — `"report"` is the only accepted
 * value today; this field is the wire's single extension
 * point (design D2).
 */
subject_kind: string, 
/**
 * Opaque Automerge canonical-heads token of the snapshot the
 * plugin proposed against (`ReportDoc::doc_heads`).
 */
base_doc_heads: string, ops: Array<ProposalOp>, 
/**
 * Human-facing rationale rendered in the adjudication UI.
 */
note: string, 
/**
 * Pending-scoped idempotency key: while a `(plugin, track,
 * idem_key)` proposal is pending, re-submits return the
 * original proposal id; resolution releases the key.
 */
idem_key: string, } } | { "ev": "proposal.resolved", "data": { track_id: TrackId, proposal_id: string, plugin_id: string, decision: ProposalDecision, } } | { "ev": "forge.scan.completed", "data": { track_id: TrackId, overlapping_prs: Array<number>, } } | { "ev": "forge.pr.opened", "data": { track_id: TrackId, pr_number: number, head_sha: string, } } | { "ev": "forge.pr.diff.read", "data": { track_id: TrackId, pr_number: number, base_sha: string, head_sha: string, artifact_path: string, } } | { "ev": "forge.pr.checks", "data": { track_id: TrackId, pr_number: number, conclusion: string, } } | { "ev": "forge.issue.read", "data": { track_id: TrackId, issue_number: number, artifact_path: string, } } | { "ev": "forge.issue.closed", "data": { track_id: TrackId, issue_number: number, } } | { "ev": "worktree.provisioned", "data": { track_id: TrackId, card_id: CardId, path: string, } } | { "ev": "worktree.committed", "data": { track_id: TrackId, card_id: CardId, commit_sha: string, branch: string, } } | { "ev": "worktree.removed", "data": { track_id: TrackId, card_id: CardId, path: string, } } | { "ev": "task.gate_result", "data": { task_id: string, idempotency_key: string, passed: boolean, failing_step?: string, exit_code?: number, log_tail: string, log_path: string, attempt: number, agent_message?: string, } };

/**
 * Where an event lives in the area → track → card hierarchy.
 *
 * `EventScope::System` is the catch-all for events that genuinely don't
 * belong to a single area/track/card (`Event::PluginState`, the
 * AreaCreated case where the area doesn't exist before the event, and
 * malformed legacy rows). Prefer the narrowest available scope.
 */
export type EventScope = { "kind": "System" } | { "kind": "Area", "id": { area: AreaId, } } | { "kind": "Track", "id": { track: TrackId, area: AreaId, } } | { "kind": "Card", "id": { card: CardId, track: TrackId, area: AreaId, } };

/**
 * Issue #250 PR 1 — 409 body for the folder-create conflict case.
 * Hand-written DTO so the frontend gets a structured shape rather
 * than the generic `{error, code}` envelope.
 */
export type FolderConflict = { folder_id: number, area_id: AreaId, conflict_path: string, conflict_kind: FolderConflictKind, };

/**
 * Issue #250 PR 1 — kind of overlap detected by the
 * `POST /api/areas/:area_id/folders` conflict check. Surfaces in the
 * 409 response body so the frontend can render a precise message
 * without re-parsing strings.
 */
export type FolderConflictKind = "equal" | "ancestor" | "descendant";

/**
 * Phase/slice PR identity carried by `forge.pr.merged`.
 */
export type ForgeMergeSubject = { phase: string, slice_id: string, pr_number: number, };

export type HarnessItem = { id: number, runtime_id: string, card_id: CardId, track_id: TrackId, thread_id: string, turn_id: string | null, item_uuid: string | null, item_type: string | null, method: string, params: string, created_at_ms: number, };

export type HarnessPhaseTag = "pending_thread_start" | "idle" | "issuing_turn" | "issuing_interrupt" | "turn_running" | "turn_completed" | "resumed" | "wedged";

export type Overlay = { id: string, plugin_id: string, 
/**
 * `"track"` or `"card"`.
 */
entity_kind: string, entity_id: string, 
/**
 * Plugin-defined string. Kernel does not interpret.
 */
kind: string, 
/**
 * Opaque JSON blob — see `Card.payload` for the rationale on the
 * explicit `unknown` override.
 */
payload: unknown, updated_at: number, };

/**
 * Position anchor for proposed block creation / moves (design §5.2.1).
 *
 * Proposals are asynchronous, so positions are expressed against
 * stable block ids — never numeric indexes (an unrelated insertion
 * would silently shift index semantics while every block rev still
 * matches). Externally-tagged serde gives `"at_start"` / `"at_end"` /
 * `{"after_block_id": "b_0001"}` on the wire; `after_block_id` may
 * reference a block created earlier in the same proposal via the
 * `temp:<temp_id>` form.
 */
export type ProposalAnchor = { "after_block_id": string } | "at_start" | "at_end";

/**
 * How a pending proposal was resolved. Two events, four decisions
 * (design §5.6): `accepted` / `rejected` / `stale` are user-driven
 * adjudications (`stale` is the accept attempt whose in-tx anchoring
 * checks failed); `withdrawn` is the submitting plugin reclaiming its
 * own pending slot — the only plugin-side exit, so quota can't be
 * pinned forever by abandoned proposals.
 *
 * Wire shape: bare lowercase string (matches the surrounding
 * event-payload enum conventions, e.g. `EditAuthor`).
 */
export type ProposalDecision = "accepted" | "rejected" | "stale" | "withdrawn";

/**
 * One proposed mutation of the track-report block document
 * (design §5.2.1). A deliberately *stricter* sibling of the
 * interactive `calm.report.blocks.*` tool DTOs: anchoring must be
 * complete because apply happens asynchronously, and the wholesale
 * `WriteMarkdown` / `Replace` shapes are excluded on purpose (full
 * overwrites and string matching cannot be meaningfully proposed).
 *
 * Field-requirement rules (`if_rev` mandatory when replacing, exactly
 * one of `block_id` / `temp_id`, anchor mandatory for creations) are
 * historical: before the channel was withdrawn in #973, these constraints
 * were enforced by its submit handler. The wire type keeps them `Option`
 * only where two legal shapes share a variant.
 */
export type ProposalOp = { "op": "upsert_block", block_id?: string, temp_id?: string, kind: string, payload: unknown, if_rev?: number, anchor?: ProposalAnchor, } | { "op": "move_block", block_id: string, if_rev: number, anchor: ProposalAnchor, } | { "op": "delete_block", block_id: string, if_rev: number, };

export type RatifyDecision = "grant" | "deny";

/**
 * A derived, addressable slice of a track report.
 */
export type ReportBlock = { id: string, kind: string, rev: number, payload: unknown, };

/**
 * Logical review subject key for `review.round`.
 */
export type ReviewSubject = { phase: string, slice_id: string, pr_number: number | null, };

/**
 * One changed frozen reference carried by a context-advance verdict.
 */
export type TaskContextChangedRef = { track_id: TrackId, block_id: string, from_rev: number, to_rev: number, from_hash: string, to_hash: string, };

/**
 * One report-block identity captured in a task context freeze.
 */
export type TaskContextRef = { track_id: TrackId, block_id: string, rev: number, hash: string, is_root: boolean, };

export type Track = { id: TrackId, area_id: AreaId, title: string, sort: number, archived_at: number | null, pinned_at: number | null, lifecycle: TrackLifecycle, 
/**
 * Wire-compatibility alias of `workspace.path`, serialized as `cwd`.
 *
 * Rust readers must use `workspace.path`; this field only preserves the
 * existing wire shape.
 */
cwd: string, 
/**
 * Template this track was created from.
 *
 * The `serde(alias)` below is a deserialization-only compatibility read
 * for pre-#1209 event-log rows; serialization emits only this name.
 */
template_id: string | null, 
/**
 * Owning plugin copied from the bound template. Immutable after creation.
 */
plugin_scope: string | null, 
/**
 * Server-owned structural marker. Public track creation cannot set this.
 */
purpose: string | null, 
/**
 * Template input is validated at creation and otherwise remains opaque.
 *
 * Carries the same deserialization-only alias as `template_id`.
 */
template_input: unknown, 
/**
 * Issue #250 PR 2 — unix-ms timestamp the track most recently
 * entered a terminal lifecycle state (Done / Canceled / Failed),
 * or `None` while the track is non-terminal. Stamped inside the
 * same transaction as the `TrackLifecycleChanged` event by
 * `track_update_tx`; cleared back to `None` on reopen
 * (Done/Canceled/Failed → Planning). The calendar window query
 * `GET /api/tracks?since&until` uses `(terminal_at IS NULL OR
 * terminal_at >= since)` to keep open tracks visible across every
 * day they span.
 *
 * Backfill semantics: rows that existed before this migration
 * stay `None` even when their lifecycle is already terminal —
 * the event log carries the original transition timestamp but
 * the migration deliberately doesn't read from `events` (mixing
 * migration with replay is fragile). A user-driven reopen →
 * re-Done cycle stamps the column with the current time, which
 * is the first defensible point.
 */
terminal_at: number | null, workspace: TrackWorkspace, created_at: number, updated_at: number, };

/**
 * One row of `GET /api/tracks/{track_id}/conversations` (#1189 §4.1).
 *
 * Its own type rather than a reuse of [`AreaConversationSummary`], which is
 * what #1189 §6 Q3 leaned towards and what the shapes turned out to require:
 * the area type's contract says "`trackTitle` is absent because every row lives
 * on one hidden track", and on a track that reasoning is simply not true. Two
 * lists with different contracts should not share one name just because their
 * current fields coincide.
 */
export type TrackConversationSummary = { 
/**
 * The assistant card's id. This is the conversation's identity everywhere,
 * and it is also the card the CARDS panel and `/api/cards/{id}/planner/*`
 * address.
 */
id: string, 
/**
 * The track this conversation lives on. Always the track in the request
 * path; carried so a client holding a bare row can navigate.
 */
trackId: string, 
/**
 * The conversation's own name, or null before it has one. Never the
 * track's title.
 */
title: string | null, 
/**
 * Always `"track-assistant"`, derived from the card's persisted marker.
 * A distinct value from the area list's `"shared-chat"` on purpose: the
 * frontend branches on it, and a shared value would route assistant rows
 * through the area chat's presentation.
 */
kind: string, 
/**
 * The live session's state, or **null when the card has no session row**.
 *
 * Nullable for the same reason as the area list's: the query LEFT JOINs so
 * a card whose session is gone (failed start, superseded runtime, shut
 * down harness) stays visible. Never fill it with an invented value.
 */
state: WorkerSessionState | null, 
/**
 * The session's last update, falling back to the card's own.
 */
updatedAt: number, };

export type TrackFsCardMeta = { created_at: number, deletable: boolean, id: CardId, kind: string, role: CardRole, sort: number, updated_at: number, };

export type TrackFsHookEvent = { created_at: number, event_id: number, hook_kind: string, kind: string, payload: unknown, };

export type TrackFsRunDetail = { events: TrackFsRunEvents, finished_at: number | null, idempotency_key: string, kind: string, requested_at: number | null, status: TrackFsRunStatus, verdict: TrackFsRunVerdict | null, worker_card_id: CardId | null, worker_card_payload: unknown | null, };

export type TrackFsRunEventRef = { created_at: number, event_id: number, kind: string, payload: unknown, };

export type TrackFsRunEvents = { completed: TrackFsRunEventRef | null, failed: TrackFsRunEventRef | null, requested: TrackFsRunEventRef | null, verdict: TrackFsRunEventRef | null, };

export type TrackFsRunIndexEntry = { finished_at: number | null, idempotency_key: string, kind: string, requested_at: number | null, status: TrackFsRunStatus, verdict: TrackFsRunVerdictSummary | null, worker_card_id: CardId | null, };

export type TrackFsRunStatus = "completed" | "failed" | "running" | "requested" | "unknown";

export type TrackFsRunVerdict = { at: number, reason: string | null, status: string, };

export type TrackFsRunVerdictSummary = { at: number, status: string, };

/**
 * Track identifier. See [`AreaId`] for the opacity contract.
 */
export type TrackId = string;

/**
 * Issue #145 — Track lifecycle state machine.
 *
 * One explicit state per track, advanced through a typed state machine
 * (see `crate::track_lifecycle`). The Planner Agent drives the happy path
 * (`draft → planning → dispatching → working → reviewing → done`);
 * the user can cancel any non-terminal state and reopen terminals;
 * worker cards have no authority to touch this field at all.
 *
 * **`archived` is intentionally NOT a lifecycle state.** Archive is
 * visibility / history management, orthogonal to execution semantics —
 * a `done`/`failed`/`canceled` track can also be archived without
 * destroying the lifecycle truth. Archival continues to live on the
 * existing `archived_at: Option<i64>` field.
 *
 * Persisted as a lowercase string in `tracks.lifecycle` (migration
 * 0012). The serde + sqlx `rename_all = "lowercase"` keeps the wire
 * and storage shape stable; ts-rs exports the matching TS union into
 * `fe/core/api/generated/wire.ts` so the frontend can render the
 * badge against the same vocabulary.
 */
export type TrackLifecycle = "draft" | "planning" | "dispatching" | "working" | "blocked" | "reviewing" | "done" | "canceled" | "failed";

/**
 * The payload persisted in a track-report card's `payload` JSON column.
 *
 * Wire shape (camelCase to match the rest of the kernel's payloads):
 *
 * ```json
 * {
 *   "schemaVersion": 3,
 *   "docRev": 7,
 *   "summary": "Refactored the dispatcher into a typed actor",
 *   "body": "# Goal\n\nReplace the ad-hoc loop with…\n\n# Progress\n..."
 * }
 * ```
 *
 * `summary` is the one-line previewable in sidebars / list views;
 * `body` is the Markdown source the TrackReportCard renders. The
 * frontend derives sections from `body` by splitting on H1 headings;
 * the storage layer does not impose a section vocabulary.
 */
export type TrackReportPayload = { 
/**
 * Tier A persistence contract — see
 * `TRACK_REPORT_PAYLOAD_SCHEMA_VERSION` in calm-truth's
 * `validation.rs`. `3` since #979 added document-wide optimistic
 * concurrency; blocks remain authoritative and `body` is their
 * flat projection. v1/v2 rows remain readable and are lazily
 * upgraded at the next persist via the CRDT-layer migrator
 * (`ReportDoc::ensure_blocks_layout`).
 */
schemaVersion: number, 
/**
 * Document-wide optimistic-concurrency revision. This is mirrored
 * from the authoritative CRDT root and increments after every
 * successful report persist (whole-document or block-level).
 */
docRev: number, 
/**
 * One-line summary used by sidebars / track-list previews. Empty
 * string is valid (means "planner agent has not produced a summary
 * yet"); the field stays a required `String` per the
 * [[required-over-option]] rule.
 */
summary: string, 
/**
 * Markdown source. Sections are derived at render time by
 * splitting at H1 (`^# `) headings; the kernel does not interpret
 * the structure.
 */
body: string, 
/**
 * Block mirror of the authoritative CRDT block map (#960 PR2).
 * Since schema v2 the CRDT `blocks`/`order` layout is the source
 * of truth; this JSON field and `body` are both projections the
 * persist boundary rewrites on every write. v1 rows may omit it.
 */
blocks?: Array<ReportBlock> | null, };

/**
 * Payload for `Event::TrackUpdated`.
 *
 * `track` is flattened to preserve the historical wire shape: the event data
 * remains the full track row at top level.
 */
export type TrackUpdatedPayload = { agent_message?: string, id: TrackId, area_id: AreaId, title: string, sort: number, archived_at: number | null, pinned_at: number | null, lifecycle: TrackLifecycle, 
/**
 * Wire-compatibility alias of `workspace.path`, serialized as `cwd`.
 *
 * Rust readers must use `workspace.path`; this field only preserves the
 * existing wire shape.
 */
cwd: string, 
/**
 * Template this track was created from.
 *
 * The `serde(alias)` below is a deserialization-only compatibility read
 * for pre-#1209 event-log rows; serialization emits only this name.
 */
template_id: string | null, 
/**
 * Owning plugin copied from the bound template. Immutable after creation.
 */
plugin_scope: string | null, 
/**
 * Server-owned structural marker. Public track creation cannot set this.
 */
purpose: string | null, 
/**
 * Template input is validated at creation and otherwise remains opaque.
 *
 * Carries the same deserialization-only alias as `template_id`.
 */
template_input: unknown, 
/**
 * Issue #250 PR 2 — unix-ms timestamp the track most recently
 * entered a terminal lifecycle state (Done / Canceled / Failed),
 * or `None` while the track is non-terminal. Stamped inside the
 * same transaction as the `TrackLifecycleChanged` event by
 * `track_update_tx`; cleared back to `None` on reopen
 * (Done/Canceled/Failed → Planning). The calendar window query
 * `GET /api/tracks?since&until` uses `(terminal_at IS NULL OR
 * terminal_at >= since)` to keep open tracks visible across every
 * day they span.
 *
 * Backfill semantics: rows that existed before this migration
 * stay `None` even when their lifecycle is already terminal —
 * the event log carries the original transition timestamp but
 * the migration deliberately doesn't read from `events` (mixing
 * migration with replay is fragile). A user-driven reopen →
 * re-Done cycle stamps the column with the current time, which
 * is the first defensible point.
 */
terminal_at: number | null, workspace: TrackWorkspace, created_at: number, updated_at: number, };

/**
 * A track's typed workspace. `path` is its single stored path.
 */
export type TrackWorkspace = { kind: TrackWorkspaceKind, 
/**
 * Absolute path.
 */
path: string, 
/**
 * One-shot, monotonic. `Some` ⇒ neither `path` nor `kind` may change
 * again.
 *
 * The system-area launchpad remains unfrozen because it is repointed by
 * `today_launchpad_ensure_tx`.
 */
frozen_at: number | null, };

/**
 * Ownership must be explicit because only managed workspaces may be recycled.
 */
export type TrackWorkspaceKind = "managed" | "attached";

/**
 * Opaque execution-session identifier.
 */
export type WorkerSessionId = string;

export type WorkerSessionKind = "terminal" | "codex" | "claude" | "shared-spec";

export type WorkerSessionProjection = { id: string, card_id: string, kind: WorkerSessionKind, agent_provider: AgentProvider | null, status: WorkerSessionState, terminal_run_id: string | null, thread_id: string | null, session_id: string | null, active_turn_id: string | null, handle_state_json: unknown | null, created_at_ms: number, updated_at_ms: number, completed_at_ms: number | null, };

/**
 * Session state machine column (`worker_sessions.state`, issue #679 §1).
 * Single runtime/session state vocabulary (`worker_sessions.state`, issue #679 §1).
 */
export type WorkerSessionState = "starting" | "running" | "idle" | "turn_pending" | "exited" | "failed" | "superseded";
