/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cards/{card_id}/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up the Terminal row a card owns. Returns 404 if the card has no
         *     terminal (yet). The UI uses this to validate a card_id cached in
         *     localStorage before attempting a WS attach to its terminal.
         */
        get: operations["get_terminal_for_card"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_card"];
        options?: never;
        head?: never;
        patch: operations["update_card"];
        trace?: never;
    };
    "/api/coves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_coves"];
        put?: never;
        post: operations["create_cove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coves/system": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Issue #175 — idempotent upsert for the singleton system cove that
         *     hosts the default Today terminal's wave + card. Returns 200 with the
         *     existing row when one is present; otherwise mints a new row and
         *     returns 201. The DB-level partial unique index on
         *     `coves(kind) WHERE kind = 'system'` enforces the at-most-one
         *     invariant as a backstop, so two tabs racing this endpoint can both
         *     safely call it: the loser of the write race catches the unique
         *     violation, re-reads the row the winner committed, and returns 200
         *     to its own caller. From the frontend's perspective both racers see a
         *     success and a populated `Cove` body — the only observable difference
         *     is the status code (201 vs 200), and `useTodayTerminal` treats both
         *     as success.
         * @description The endpoint exists so the frontend's `useTodayTerminal` hook can
         *     bootstrap a default terminal without exposing the underlying system
         *     cove to the regular `POST /api/coves` surface (which the sidebar
         *     "+ New cove" affordance consumes and which would otherwise need a
         *     reserved-name policy).
         */
        post: operations["get_or_create_system_cove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coves/{cove_id}/waves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_waves_by_cove"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coves/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_cove"];
        options?: never;
        head?: never;
        patch: operations["update_cove"];
        trace?: never;
    };
    "/api/fs/listdir": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listdir"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_overlays"];
        put?: never;
        post: operations["upsert_overlay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overlays/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_overlay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_plugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["install_plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_plugin_views"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_plugin_detail"];
        put?: never;
        post?: never;
        delete: operations["uninstall_plugin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_plugin_config"];
        trace?: never;
    };
    "/api/plugins/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disable_plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enable_plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tail_plugin_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reload_plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/resources/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_plugin_view_html"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotate_plugin_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/tool-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["plugin_tool_call"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_settings"];
        put: operations["put_settings"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/version": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_version"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_wave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waves/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_wave_detail"];
        put?: never;
        post?: never;
        delete: operations["delete_wave"];
        options?: never;
        head?: never;
        patch: operations["update_wave"];
        trace?: never;
    };
    "/api/waves/{wave_id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_cards_by_wave"];
        put?: never;
        post: operations["create_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waves/{wave_id}/codex-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_codex_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waves/{wave_id}/terminal-cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_terminal_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Card: {
            /** Format: int64 */
            created_at: number;
            id: string;
            /**
             * @description `"terminal"` for built-in PTY cards, `"plugin:<plugin-id>:<view-id>"`
             *     for plugin-provided cards. Kernel never interprets beyond that prefix.
             */
            kind: string;
            /**
             * @description Opaque JSON blob — ts-rs would otherwise emit `unknown` via the
             *     `serde-json-impl` feature, but we pin it explicitly so a future
             *     feature-flag change can't silently widen / narrow the surface.
             */
            payload: Record<string, never>;
            /** Format: double */
            sort: number;
            /** Format: int64 */
            updated_at: number;
            wave_id: string;
        };
        CardPatch: {
            kind?: string | null;
            payload?: Record<string, never> | null;
            /** Format: double */
            sort?: number | null;
        };
        Cove: {
            color: string;
            /** Format: int64 */
            created_at: number;
            id: string;
            /**
             * @description Issue #175 — `User` for sidebar-visible coves, `System` for the
             *     internal singleton that hosts the default Today terminal's wave.
             *     Mirror of `CardRole` precedent on `Card`: persisted at storage
             *     time via DB DEFAULT, never accepted on `POST /api/coves` (which
             *     has no `kind` field — `NewCove` deliberately omits it).
             *
             *     `#[serde(default)]` so wire payloads emitted before #175 landed
             *     (event-log replay fixtures, old test seeds) parse as `User`
             *     without forcing a fixture rewrite — matches the DB DEFAULT in
             *     migration 0009.
             */
            kind?: components["schemas"]["CoveKind"];
            name: string;
            /** Format: double */
            sort: number;
            /** Format: int64 */
            updated_at: number;
        };
        /**
         * @description Issue #175 — visibility / ownership gate persisted on each cove.
         *
         *     The kind decides whether the row participates in the user-visible
         *     workspace surface (sidebar nav, default `GET /api/coves`) or is an
         *     internal kernel-owned entity hidden from the regular UI.
         *
         *       * [`CoveKind::User`] is the default for every existing cove and
         *         every cove minted via `POST /api/coves`. There is no
         *         authorization difference from the pre-#175 product — these are
         *         the only coves the user ever sees in the sidebar.
         *       * [`CoveKind::System`] is a singleton (DB-enforced via a partial
         *         unique index in migration 0009) hosting the default Today
         *         terminal's wave + card. Created via `cove_create_system_tx`,
         *         reachable via the idempotent `POST /api/coves/system` upsert.
         *         `GET /api/coves` filters these out by default — opt-in via
         *         `?include_system=true`. The user never interacts with this
         *         cove directly; it's storage scaffolding, not UI.
         *
         *     Persisted as a lowercase string in `coves.kind` (migration 0009).
         *     The serde + sqlx `rename_all = "lowercase"` keeps the wire / storage
         *     shape stable; ts-rs exports the matching TS union
         *     (`"user" | "system"`) into `web/src/api/generated-events.ts` so the
         *     frontend can validate against it. UI types intentionally don't
         *     surface `kind` — the server's default filter already hides system
         *     coves, so a one-line `.filter(c => c.kind === 'user')` in CalmApp /
         *     router belt-and-suspenders is the only frontend consumer.
         * @enum {string}
         */
        CoveKind: "user" | "system";
        CovePatch: {
            color?: string | null;
            name?: string | null;
            /** Format: double */
            sort?: number | null;
        };
        /**
         * @description Body payload accepted by `POST /api/waves/:wave_id/cards`.
         *
         *     Two mutually-exclusive paths:
         *       * **Direct create** — `kind`, `sort`, `payload`, `title` set (legacy
         *         pre-M2 wire). The kernel writes the row verbatim.
         *       * **`via_tool_call`** — kernel invokes the plugin's tool, extracts the
         *         `ui://` resource URI from `_meta.ui.resourceUri`, persists a Card with
         *         `kind = <resource_uri>` and `payload = structuredContent`.
         *
         *     When both are sent, `via_tool_call` wins. Documented in this module's
         *     header. We keep the legacy fields alongside via `#[serde(flatten)]` so
         *     existing clients (web-calm AddPanel for terminal/doc cards) keep working
         *     unchanged.
         */
        CreateCardBody: {
            /**
             * @description Legacy direct-create fields. Mirrors `NewCard` shape; `wave_id` is
             *     taken from the path so we omit it here.
             */
            kind?: string | null;
            payload?: Record<string, never> | null;
            /** Format: double */
            sort?: number | null;
            via_tool_call?: null | components["schemas"]["ViaToolCall"];
        };
        DirEntry: {
            is_dir: boolean;
            name: string;
        };
        /**
         * @description JSON shape returned for every error response — `{error, code}`.
         *     Mirrors the body produced by `CalmError::into_response`. Hand-written
         *     duplicate of the in-line `json!` body so OpenAPI consumers see a
         *     concrete schema.
         */
        ErrorBody: {
            /**
             * @description Stable machine-readable code — one of `not_found`, `conflict`,
             *     `idempotency_collision`, `bad_request`, `unauthorized`,
             *     `forbidden`, `plugin_install`, `plugin_permission`,
             *     `plugin_conflict`, `plugin_kernel_too_old`, `db_error`,
             *     `io_error`, `serde_error`, `internal`, `forbidden_tool`,
             *     `not_a_card_tool`, `tool_call_failed`.
             */
            code: string;
            /** @description Human-readable error message. */
            error: string;
        };
        InstallBody: {
            source: components["schemas"]["InstallSource"];
        };
        InstallSource: {
            /** @enum {string} */
            kind: "local_path";
            path: string;
        } | {
            /** @enum {string} */
            kind: "other";
        };
        ListdirResponse: {
            /**
             * @description Children, sorted: directories first, then case-insensitive alpha.
             *     Hidden entries (leading dot) are filtered out.
             */
            entries: components["schemas"]["DirEntry"][];
            /** @description Canonical absolute path of the parent directory, or `null` at root. */
            parent?: string | null;
            /** @description Canonical absolute path of the listed directory. */
            path: string;
        };
        NewCard: {
            kind: string;
            payload?: Record<string, never>;
            /** Format: double */
            sort?: number | null;
            /**
             * @description Defaulted so the REST handler can override from the `:wave_id` path
             *     param without forcing every client body to repeat it. Direct repo
             *     callers must still set this — passing "" produces a NotFound.
             */
            wave_id?: string;
        };
        /**
         * @description Body for `POST /api/waves/:wave_id/codex-cards`.
         *
         *     Deliberately omits `kind` (always `"codex"`) and `payload` (the kernel
         *     stamps `{schemaVersion, terminal_id, cwd?, prompt?}` itself). Empty
         *     `cwd` falls back to `$HOME` then the server's cwd.
         *
         *     `prompt` is the hands-free entry point: when non-empty, the kernel
         *       1. passes it to codex CLI as the positional `[PROMPT]` arg
         *          (shell-single-quoted), which mounts the TUI with the composer
         *          pre-filled,
         *       2. writes a per-spawn `$CODEX_HOME/config.toml` that silences the
         *          three first-run dialogs (approval, sandbox, project trust) so
         *          injected stdin lands on the composer instead of a modal, and
         *       3. stamps `prompt` onto the card payload — the
         *          `codex_auto_submit` subscriber reads it and, once codex emits
         *          `hook.codex.session_start`, opens a kernel-private connection
         *          to the daemon and injects a `\r` so the composer auto-submits.
         *
         *     Empty / absent `prompt` reverts to the user-initiated flow: codex
         *     boots, the composer is empty, the user types and hits Enter.
         *
         *     Note: the old `initial_prompt` field (which had been a documented
         *     no-op since the codex-TUI port) was removed; serde rejects unknown
         *     fields with the default config, so a stale caller that still sends
         *     it will get a 422 — that's the intended fail-loud signal to update
         *     the caller. The interactive `prompt` channel is the one place
         *     callers should be putting text now.
         */
        NewCodexCardBody: {
            /**
             * @description Working directory codex runs in. Empty string or missing → `$HOME`
             *     (then `cwd` of server).
             */
            cwd?: string | null;
            /**
             * @description Hands-free seed prompt. When set and non-empty, codex boots with
             *     its composer pre-filled and the kernel auto-submits the composer
             *     once codex's session is constructed. See the struct doc for the
             *     full mechanism.
             */
            prompt?: string | null;
            /**
             * Format: double
             * @description Sort order within the wave. `None` defaults to "append to end".
             */
            sort?: number | null;
        };
        NewCove: {
            color: string;
            name: string;
            /**
             * Format: double
             * @description If absent, server appends to end.
             */
            sort?: number | null;
        };
        NewOverlay: {
            entity_id: string;
            entity_kind: string;
            kind: string;
            payload: Record<string, never>;
            plugin_id: string;
        };
        /**
         * @description Body for `POST /api/waves/:wave_id/terminal-cards`.
         *
         *     Deliberately omits `kind` (always `"terminal"`) and `payload` (the kernel
         *     stamps `{schemaVersion, terminal_id}` itself). Empty `program` falls back
         *     to `$SHELL` then `/bin/sh`; empty `cwd` falls back to `$HOME` then the
         *     server's cwd. `env` is merged into the daemon's environment as additional
         *     vars on top of `TERM` / `COLORTERM` / inherited.
         */
        NewTerminalCardBody: {
            /** @description Empty string or missing → `$HOME` (then cwd of server). */
            cwd?: string;
            /** @description Extra env on top of the inherited set. JSON object: `{"FOO":"bar"}`. */
            env?: Record<string, never>;
            /** @description Empty string or missing → `$SHELL` (then `/bin/sh`). */
            program?: string;
            /**
             * Format: double
             * @description Sort order within the wave. `None` defaults to "append to end".
             */
            sort?: number | null;
        };
        NewWave: {
            cove_id: string;
            /** Format: double */
            sort?: number | null;
            title: string;
        };
        Overlay: {
            entity_id: string;
            /** @description `"wave"` or `"card"`. */
            entity_kind: string;
            id: string;
            /** @description Plugin-defined string. Kernel does not interpret. */
            kind: string;
            /**
             * @description Opaque JSON blob — see `Card.payload` for the rationale on the
             *     explicit `unknown` override.
             */
            payload: Record<string, never>;
            plugin_id: string;
            /** Format: int64 */
            updated_at: number;
        };
        OverlayDeleteBody: {
            entity_id: string;
            entity_kind: string;
            kind: string;
            plugin_id: string;
        };
        OverlayQuery: {
            /**
             * @description Optional. When omitted, returns every overlay of `entity_kind`
             *     across the workspace — the sidebar uses this form to render
             *     accurate per-wave status without fetching each wave's detail.
             */
            entity_id?: string | null;
            entity_kind: string;
        };
        Plugin: {
            enabled: boolean;
            id: string;
            install_path: string;
            /** Format: int64 */
            installed_at: number;
            manifest: Record<string, never>;
            /** Format: int64 */
            updated_at: number;
            user_config: Record<string, never>;
            version: string;
        };
        /**
         * @description Single-plugin detail returned by GET-by-id, install, enable, disable,
         *     config-patch, and reload. The full manifest blob rides along so the UI can
         *     render version/author/views without a separate fetch.
         */
        PluginDetail: {
            enabled: boolean;
            id: string;
            /** Format: int64 */
            installed_at: number;
            last_error?: string | null;
            manifest: Record<string, never>;
            state: string;
            /** Format: int64 */
            updated_at: number;
            user_config: Record<string, never>;
            version: string;
        };
        /**
         * @description Compact row used by `GET /api/plugins`. Pairs the persisted `Plugin` row
         *     with the runtime status the supervisor knows about. The full manifest is
         *     excluded here to keep the list payload cheap; callers needing the manifest
         *     hit `GET /api/plugins/:id`.
         */
        PluginListItem: {
            enabled: boolean;
            id: string;
            last_error?: string | null;
            manifest_description?: string | null;
            manifest_name: string;
            /**
             * @description Wire-name string per design §7.1: `running | spawning | crashed |
             *     disabled | installing | installed`.
             */
            state: string;
            version: string;
        };
        /**
         * @description Wire-shape: a flat string map of key -> value. We use `BTreeMap` for
         *     deterministic ordering in the response so the OpenAPI spec consumers
         *     see stable test diffs.
         */
        SettingsBag: {
            settings: {
                [key: string]: string;
            };
        };
        /**
         * @description Request body for `PUT /api/settings`. Values are `Option<String>` so
         *     the client can clear a key by sending `null`. Empty strings are also
         *     treated as deletes; see module docs for the rationale.
         */
        SettingsPutBody: {
            settings?: {
                [key: string]: string | null;
            };
        };
        Terminal: {
            card_id: string;
            /** Format: int64 */
            created_at: number;
            cwd: string;
            daemon_handle?: string | null;
            env: Record<string, never>;
            id: string;
            /**
             * Format: int64
             * @description Daemon process id, captured by `spawn_daemon_for` after `cmd.spawn()`.
             *     Used by the orphan-terminal sweeper (`terminal_sweeper`) as the
             *     SIGTERM fallback target when the graceful `ClientMsg::Kill` path
             *     fails. `None` for rows that predate Scope C or for which the spawn
             *     returned no pid (kernel-level edge case).
             */
            pid?: number | null;
            program: string;
        };
        /**
         * @description M5: AppBridge → kernel tool-call wire body. Mirrors the JSON-RPC
         *     `tools/call` params shape so the web-calm helper can hand it through
         *     verbatim from the iframe-side `app.callServerTool({ name, arguments })`.
         *
         *     Scope β: an optional `call_id` is threaded through to every event the
         *     kernel writes while servicing this call. Each downstream `events.row`
         *     records `correlation = "user_tool_call:<call_id>"` so multi-step
         *     dispatches (e.g. a plugin tool that issues several overlay writes) can
         *     be grouped after the fact (design doc §9). The frontend mints the id;
         *     the kernel never inspects its content beyond formatting it into the
         *     correlation string.
         */
        ToolCallBody: {
            arguments?: Record<string, never>;
            /**
             * @description Optional caller-supplied tracing id. Omitted on legacy callers; the
             *     resulting events still write but with `correlation = NULL`.
             */
            call_id?: string | null;
            name: string;
        };
        /**
         * @description Response shape for `GET /api/version`. camelCase on the wire so it lines
         *     up with the rest of the TypeScript-facing surface.
         */
        VersionInfo: {
            apiVersion: string;
            buildSha?: string | null;
            /** @description UUID v4 minted once per process boot. See module doc. */
            dbInstanceId: string;
            kernelVersion: string;
            mcpProtocolVersion: string;
            /** Format: int32 */
            minWebCompatVersion: number;
            /** Format: int32 */
            syncEventVersion: number;
        };
        ViaToolCall: {
            arguments?: Record<string, never>;
            plugin_id: string;
            tool_name: string;
        };
        /**
         * @description One entry in the `/api/plugins/views` catalog. Used by Slice G's AddPanel.
         *
         *     The canonical identifier is the MCP Apps `ui://<plugin>/<view>` URI in
         *     `resource_uri`. The frontend parses the `(plugin_id, view_id)` pair off
         *     it lazily via `parsePluginCardKind`.
         */
        ViewCatalogEntry: {
            default_size?: null | components["schemas"]["ViewSizeWire"];
            icon?: string | null;
            /**
             * @description Canonical MCP Apps URI: `ui://<plugin_id>/<view_id>`. Always present —
             *     computed kernel-side so the frontend doesn't have to redo the join.
             */
            resource_uri: string;
            /** @description `"card"` for M3 — wave/cove are banned per design §10. */
            scope: string;
            title: string;
        };
        ViewSizeWire: {
            /** Format: int32 */
            h: number;
            /** Format: int32 */
            min_h?: number | null;
            /** Format: int32 */
            min_w?: number | null;
            /** Format: int32 */
            w: number;
        };
        Wave: {
            /** Format: int64 */
            archived_at?: number | null;
            cove_id: string;
            /** Format: int64 */
            created_at: number;
            id: string;
            /** Format: double */
            sort: number;
            title: string;
            /** Format: int64 */
            updated_at: number;
        };
        /**
         * @description What a Wave detail page renders: the wave itself plus its cards and
         *     any overlays scoped to the wave (status/progress badges) and its cards.
         */
        WaveDetail: {
            cards: components["schemas"]["Card"][];
            overlays: components["schemas"]["Overlay"][];
            wave: components["schemas"]["Wave"];
        };
        WavePatch: {
            /**
             * Format: int64
             * @description Pass `Some(Some(ts))` to archive, `Some(None)` to unarchive,
             *     or omit (`None`) to leave alone.
             */
            archived_at?: number | null;
            /** Format: double */
            sort?: number | null;
            title?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_terminal_for_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card id (must be a terminal card) */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Terminal row for this card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Terminal"];
                };
            };
            /** @description Card has no terminal yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardPatch"];
            };
        };
        responses: {
            /** @description Card updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_coves: {
        parameters: {
            query?: {
                /**
                 * @description When true, also include `kind='system'` coves in the response.
                 *     Default false — the sidebar / Today UI consume the filtered list
                 *     and never need the system cove. Documented opt-in for debug surfaces
                 *     and integration tests.
                 */
                include_system?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all coves (filtered to `kind='user'` unless `include_system=true` is set) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cove"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_cove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewCove"];
            };
        };
        responses: {
            /** @description Cove created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cove"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_or_create_system_cove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System cove already existed; returned the existing row */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cove"];
                };
            };
            /** @description System cove minted */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cove"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_waves_by_cove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cove id */
                cove_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waves under cove */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wave"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_cove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cove id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cove deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cove is system-owned and cannot be deleted via REST */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Cove not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_cove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cove id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CovePatch"];
            };
        };
        responses: {
            /** @description Cove updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cove"];
                };
            };
            /** @description Cove not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    listdir: {
        parameters: {
            query?: {
                /** @description Absolute path to list; omitted → $HOME */
                path?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Directory listing */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListdirResponse"];
                };
            };
            /** @description Path doesn't exist or is not a directory */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Read permission denied */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_overlays: {
        parameters: {
            query: {
                entity_kind: string;
                /**
                 * @description Optional. When omitted, returns every overlay of `entity_kind`
                 *     across the workspace — the sidebar uses this form to render
                 *     accurate per-wave status without fetching each wave's detail.
                 */
                entity_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overlays for an entity (or all of a kind when entity_id is omitted) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overlay"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    upsert_overlay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewOverlay"];
            };
        };
        responses: {
            /** @description Overlay upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overlay"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_overlay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayDeleteBody"];
            };
        };
        responses: {
            /** @description Overlay deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_plugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installed plugins with their runtime state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginListItem"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    install_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallBody"];
            };
        };
        responses: {
            /** @description Plugin installed (disabled by default) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Manifest invalid / unsupported source */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin id already installed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Manifest min_kernel_version exceeds kernel version */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_plugin_views: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog of views from currently enabled plugins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewCatalogEntry"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_plugin_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin detail (manifest + state) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    uninstall_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin uninstalled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    patch_plugin_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        /** @description Free-form user-config JSON object */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Config updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    disable_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin disabled and stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Stop failed / internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    enable_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin enabled and spawned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Manifest min_kernel_version exceeds kernel version */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Spawn failed / internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    tail_plugin_log: {
        parameters: {
            query?: {
                n?: number | null;
            };
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent stderr lines (newest last) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reload_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manifest reloaded + plugin restarted if enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Manifest invalid / id mismatch after reload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Manifest min_kernel_version exceeds kernel version */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_plugin_view_html: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
                /** @description View id within the plugin manifest */
                view_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MCP-App HTML (Content-Type: text/html;profile=mcp-app) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html;profile=mcp-app": string;
                };
            };
            /** @description Malformed ui:// URI */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin or view not found / asset missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description I/O error reading asset */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    rotate_plugin_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Rotate failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    plugin_tool_call: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolCallBody"];
            };
        };
        responses: {
            /** @description Tool result JSON (shape depends on dispatched neige.* callback) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Non-neige.* tool requested from iframe */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin not running */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current settings map (string→string) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBag"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    put_settings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SettingsPutBody"];
            };
        };
        responses: {
            /** @description Settings replaced; returns the resulting bag */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SettingsBag"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_version: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Kernel + protocol version metadata */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["VersionInfo"];
                };
            };
        };
    };
    create_wave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWave"];
            };
        };
        responses: {
            /** @description Wave created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wave"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_wave_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wave detail (wave + its cards + overlays) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaveDetail"];
                };
            };
            /** @description Wave not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_wave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wave deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wave not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_wave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WavePatch"];
            };
        };
        responses: {
            /** @description Wave updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wave"];
                };
            };
            /** @description Wave not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_cards_by_wave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id */
                wave_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cards in wave (sorted) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id this card belongs to */
                wave_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardBody"];
            };
        };
        responses: {
            /** @description Card created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Missing `kind` and no `via_tool_call` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin lacks `permissions.cards_create` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin not running / not in registry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Tool returned no `_meta.ui.resourceUri` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin tool call failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_codex_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id to create the codex card under */
                wave_id: string;
            };
            cookie?: never;
        };
        /** @description Optional body — empty means use defaults */
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewCodexCardBody"];
            };
        };
        responses: {
            /** @description Card + linked terminal created atomically; codex daemon spawned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Wave not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Daemon spawn failed (rows are persisted; sweeper reaps within ~60s) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_terminal_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id to create the terminal card under */
                wave_id: string;
            };
            cookie?: never;
        };
        /** @description Optional body — empty means use defaults */
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTerminalCardBody"];
            };
        };
        responses: {
            /** @description Card + linked terminal created atomically; daemon spawned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Wave not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Daemon spawn failed (rows are persisted; sweeper reaps within ~60s) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
