// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daemon-side back-pressure policy hint. The first wave only encodes the
 * shape; nothing in this PR ever sends a `Backpressure` frame.
 */
export type BackpressurePolicy = "LatestOnly" | "SnapshotRequired" | "Close";

/**
 * Single cell's pixel footprint as the client measured it. Sent only when
 * it materially differs from the daemon-side default and the client wants
 * pixel-accurate image alignment.
 */
export type CellSize = { width: number, height: number, };

/**
 * What the client can decode / display. The daemon validates the
 * intersection during handshake (e.g. no `Vt` in `render_encodings` →
 * [`ProtocolErrorCode::UnsupportedEncoding`]).
 */
export type ClientCapabilities = { render_encodings: Array<RenderEncoding>, supports_scrollback: boolean, supports_sixel: boolean, supports_images: boolean, };

export type ClientMsg = { "ClientHello": { protocol_version: number, terminal_id: string, client_id: string, desired_size: PtySize, cell_size: CellSize | null, initial_scrollback: InitialScrollback, resume_from: ResumeFrom | null, role_hint: Role | null, capabilities: ClientCapabilities, } } | { "Input": Array<number> } | { "ResizeCommit": { epoch: number, cols: number, rows: number, } } | "OwnerClaim" | "OwnerRelease" | { "RenderAck": { render_rev: number, pty_seq: number | null, } } | "Kill" | { "ChatUserMessage": { content: string, } } | "ChatStop" | { "AnswerQuestion": { question_id: string, answers: { [key in string]: string }, } };

export type DaemonMsg = { "ServerHello": { protocol_version: number, terminal_id: string, session_id: string, client_role: Role, owner_client_id: string | null, pty_size: PtySize, pty_seq_head: number, pty_seq_tail: number, render_rev: number, snapshot: RenderSnapshot, history_gap: HistoryGap | null, } } | { "RenderSnapshot": RenderSnapshot } | { "RenderPatch": RenderPatch } | { "ResizeApplied": { epoch: number, pty_seq: number, render_rev: number, cols: number, rows: number, } } | { "OwnerChanged": { owner_client_id: string | null, } } | { "Backpressure": { policy: BackpressurePolicy, } } | { "SnapshotRequired": { reason: string, } } | { "TerminalExited": { code: number | null, pty_seq: number, render_rev: number, } } | { "ProtocolError": { code: ProtocolErrorCode, message: string, expected_version: number | null, } } | { "HelloChat": { replay: Array<string>, } } | { "ChatEvent": { json: string, } } | { "ChildExited": { code: number | null, } };

/**
 * Communicates to the client that its requested resume cursor was older
 * than what the daemon still has buffered. `requires_snapshot` is always
 * `true` in this PR (we always re-send the snapshot rather than a partial
 * catch-up).
 */
export type HistoryGap = { requested_render_rev: number | null, requested_pty_seq: number | null, earliest_render_rev: number, earliest_pty_seq: number, requires_snapshot: boolean, };

/**
 * How much pre-attach history the client wants in the
 * [`DaemonMsg::ServerHello`] snapshot. `None` = just the current viewport;
 * `All` = everything the daemon still has; `Lines(n)` = up to n lines of
 * scrollback (whole-chunk granularity in this PR, may tighten to
 * line-granular when the VT model lands).
 */
export type InitialScrollback = "None" | "All" | { "Lines": number };

/**
 * Typed codes for [`DaemonMsg::ProtocolError`]. Distinct from a free-form
 * string so the client can branch on the error class (e.g. show
 * "upgrade required" for `UnsupportedVersion`).
 */
export type ProtocolErrorCode = "UnsupportedVersion" | "NotOwner" | "BadSequence" | "SnapshotMissing" | "UnsupportedEncoding" | "BadHandshake";

/**
 * PTY viewport dimensions plus an optional pixel-size hint. The pixel
 * fields are only consulted by programs that draw inline images (sixel /
 * kitty graphics); most clients leave them `None`.
 */
export type PtySize = { cols: number, rows: number, pixel_width: number | null, pixel_height: number | null, };

/**
 * Render-plane payload encoding. Today the daemon only ever advertises
 * [`RenderEncoding::Vt`] (raw escape-sequence bytes); the enum exists so
 * later additions (cell-grid diffs, sixel images, ...) don't require a
 * fresh `FRAME_VERSION` bump.
 */
export type RenderEncoding = "Vt";

/**
 * Incremental render-plane update. `prev_render_rev` lets the client
 * detect a gap (its last-known `render_rev` doesn't match) and request a
 * fresh [`RenderSnapshot`].
 */
export type RenderPatch = { render_rev: number, prev_render_rev: number, pty_seq: number, encoding: RenderEncoding, data: Array<number>, };

/**
 * Self-contained snapshot of the current render state. Sent inside
 * [`DaemonMsg::ServerHello`] and as a standalone frame when the daemon
 * decides the client needs a hard resync (typically because the requested
 * resume cursor fell off the history window).
 */
export type RenderSnapshot = { render_rev: number, pty_seq: number, cols: number, rows: number, encoding: RenderEncoding, data: Array<number>, scrollback: Array<number> | null, };

/**
 * Reconnect cursor — the latest `render_rev` and/or `pty_seq` the client
 * already has. The daemon decides whether it can replay a delta from there
 * or must send a fresh snapshot (in which case a
 * [`HistoryGap`] is included in `ServerHello`).
 */
export type ResumeFrom = { render_rev: number | null, pty_seq: number | null, };

/**
 * Per-connection role assigned by the daemon's `OwnerRegistry`. The first
 * successful handshake on a freshly-spawned daemon becomes the
 * [`Role::Owner`]; subsequent clients default to [`Role::Observer`] and can
 * promote themselves with [`ClientMsg::OwnerClaim`] (hostile takeover —
 * the daemon never negotiates).
 */
export type Role = "Owner" | "Observer";
