// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Daemon-side back-pressure policy hint. The first wave only encodes the
 * shape; nothing in this PR ever sends a `Backpressure` frame.
 */
export type BackpressurePolicy = "LatestOnly" | "SnapshotRequired" | "Close";

/**
 * Single cell's pixel footprint as the client measured it. Sent only when
 * it materially differs from the daemon-side default and the client wants
 * pixel-accurate image alignment.
 */
export type CellSize = { width: number, height: number, };

/**
 * What the client can decode / display. The daemon validates the
 * intersection during handshake (e.g. no `Vt` in `render_encodings` →
 * [`ProtocolErrorCode::UnsupportedEncoding`]).
 */
export type ClientCapabilities = { render_encodings: Array<RenderEncoding>, supports_scrollback: boolean, supports_sixel: boolean, supports_images: boolean, 
/**
 * When true, this client is trusted to send [`ClientMsg::Input`]
 * frames even when it is not the owner. Intended ONLY for
 * kernel-originated clients connecting over a kernel-private unix
 * domain socket (e.g. a future task-dispatch platform's
 * `DaemonClient::inject_stdin`).
 *
 * Scope: only [`ClientMsg::Input`] is relaxed. [`ClientMsg::ResizeCommit`]
 * and [`ClientMsg::Kill`] continue to require owner role even when
 * this flag is set — the kernel relays input on behalf of an agent
 * but is not itself the source of truth for viewport / lifecycle.
 *
 * # Trust model
 *
 * The daemon itself does NOT verify this flag — it trusts whatever
 * the ClientHello asserts. Authorization is enforced at the
 * ingress, not at the daemon:
 *
 * - **Kernel-private unix socket** (intended trusted ingress): the
 *   kernel's own `DaemonClient` may set this to `true` when it
 *   needs to inject stdin to a non-owner session (e.g. agent
 *   auto-submit). This socket never crosses a network boundary.
 * - **WebSocket bridge** (`crates/calm-server/src/ws/terminal.rs`,
 *   `pump`'s up arm): THIS IS AN UNTRUSTED NETWORK SURFACE. Any
 *   browser that can reach `/api/terminals/:id` can frame a
 *   `ClientHello` with arbitrary capabilities. The bridge MUST
 *   zero this field on every ClientHello before forwarding to the
 *   daemon. Without that strip a browser could forge
 *   `kernel_originated_input: true` and write arbitrary bytes to
 *   another user's PTY while connected as an Observer.
 *
 * Wire default is `false`; older peers that don't serialize this
 * field decode as `false` thanks to `#[serde(default)]`. Any
 * future ingress that proxies a `ClientHello` over a non-trusted
 * boundary MUST sanitize this field before forwarding to the
 * daemon.
 */
kernel_originated_input: boolean, };

export type ClientMsg = { "ClientHello": { protocol_version: number, terminal_id: string, client_id: string, desired_size: PtySize, cell_size: CellSize | null, initial_scrollback: InitialScrollback, resume_from: ResumeFrom | null, role_hint: Role | null, capabilities: ClientCapabilities, } } | { "Input": { data: Array<number>, input_seq: number, } } | { "ResizeCommit": { epoch: number, cols: number, rows: number, } } | "OwnerClaim" | "OwnerRelease" | { "RenderAck": { render_rev: number, pty_seq: number | null, } } | "Kill" | { "ChatUserMessage": { content: string, } } | "ChatStop" | { "AnswerQuestion": { question_id: string, answers: { [key in string]: string }, } } | { "TerminalThemeUpdate": { fg: [number, number, number], bg: [number, number, number], } };

export type DaemonMsg = { "ServerHello": { protocol_version: number, terminal_id: string, session_id: string, client_role: Role, owner_client_id: string | null, pty_size: PtySize, pty_seq_head: number, pty_seq_tail: number, render_rev: number, snapshot: RenderSnapshot, history_gap: HistoryGap | null, is_child_ready: boolean, } } | { "RenderSnapshot": RenderSnapshot } | { "RenderPatch": RenderPatch } | { "ResizeApplied": { epoch: number, pty_seq: number, render_rev: number, cols: number, rows: number, } } | { "OwnerChanged": { owner_client_id: string | null, } } | { "Backpressure": { policy: BackpressurePolicy, } } | { "SnapshotRequired": { reason: string, } } | { "TerminalExited": { code: number | null, pty_seq: number, render_rev: number, } } | { "ProtocolError": { code: ProtocolErrorCode, message: string, expected_version: number | null, } } | { "ChildReady": { pty_seq: number, render_rev: number, } } | { "InputAck": { input_seq: number, } } | { "HelloChat": { replay: Array<string>, } } | { "ChatEvent": { json: string, } } | { "ChildExited": { code: number | null, } };

/**
 * Communicates to the client that its requested resume cursor was older
 * than what the daemon still has buffered. `requires_snapshot` is always
 * `true` in this PR (we always re-send the snapshot rather than a partial
 * catch-up).
 */
export type HistoryGap = { requested_render_rev: number | null, requested_pty_seq: number | null, earliest_render_rev: number, earliest_pty_seq: number, requires_snapshot: boolean, };

/**
 * How much pre-attach history the client wants in the
 * [`DaemonMsg::ServerHello`] snapshot. `None` = just the current viewport;
 * `All` = everything the daemon still has; `Lines(n)` = up to n lines of
 * scrollback (whole-chunk granularity in this PR, may tighten to
 * line-granular when the VT model lands).
 */
export type InitialScrollback = "None" | "All" | { "Lines": number };

/**
 * Typed codes for [`DaemonMsg::ProtocolError`]. Distinct from a free-form
 * string so the client can branch on the error class (e.g. show
 * "upgrade required" for `UnsupportedVersion`).
 */
export type ProtocolErrorCode = "UnsupportedVersion" | "NotOwner" | "BadSequence" | "SnapshotMissing" | "UnsupportedEncoding" | "BadHandshake";

/**
 * PTY viewport dimensions plus an optional pixel-size hint. The pixel
 * fields are only consulted by programs that draw inline images (sixel /
 * kitty graphics); most clients leave them `None`.
 */
export type PtySize = { cols: number, rows: number, pixel_width: number | null, pixel_height: number | null, };

/**
 * Render-plane payload encoding. Today the daemon only ever advertises
 * [`RenderEncoding::Vt`] (raw escape-sequence bytes); the enum exists so
 * later additions (cell-grid diffs, sixel images, ...) don't require a
 * fresh `FRAME_VERSION` bump.
 */
export type RenderEncoding = "Vt";

/**
 * Incremental render-plane update. `prev_render_rev` lets the client
 * detect a gap (its last-known `render_rev` doesn't match) and request a
 * fresh [`RenderSnapshot`].
 */
export type RenderPatch = { render_rev: number, prev_render_rev: number, pty_seq: number, encoding: RenderEncoding, data: Array<number>, };

/**
 * Self-contained snapshot of the current render state. Sent inside
 * [`DaemonMsg::ServerHello`] and as a standalone frame when the daemon
 * decides the client needs a hard resync (typically because the requested
 * resume cursor fell off the history window).
 */
export type RenderSnapshot = { render_rev: number, pty_seq: number, cols: number, rows: number, encoding: RenderEncoding, data: Array<number>, scrollback: Array<number> | null, };

/**
 * Reconnect cursor — the latest `render_rev` and/or `pty_seq` the client
 * already has. The daemon decides whether it can replay a delta from there
 * or must send a fresh snapshot (in which case a
 * [`HistoryGap`] is included in `ServerHello`).
 */
export type ResumeFrom = { render_rev: number | null, pty_seq: number | null, };

/**
 * Per-connection role assigned by the daemon's `OwnerRegistry`. The first
 * successful handshake on a freshly-spawned daemon becomes the
 * [`Role::Owner`]; subsequent clients default to [`Role::Observer`] and can
 * promote themselves with [`ClientMsg::OwnerClaim`] (hostile takeover —
 * the daemon never negotiates).
 */
export type Role = "Owner" | "Observer";

/**
 * Default foreground / background RGB the daemon advertises to the PTY
 * child in reply to OSC 10/11 color queries (#177). Plumbed two ways:
 *
 * 1. As CLI args (`--terminal-fg`/`--terminal-bg`) on daemon spawn so
 *    the model can answer codex's startup probe before the first PTY
 *    chunk lands.
 * 2. As [`ClientMsg::TerminalThemeUpdate`] when the browser toggles
 *    theme mid-session — the daemon updates the model's defaults and
 *    (when the child has DECSET 1004) writes `ESC[I` so a focus-aware
 *    TUI re-queries OSC 10/11; the daemon's vte parser then
 *    synthesizes the solicited reply (#305).
 *
 * Each channel is a plain u8 (8-bit per channel); the daemon expands
 * to xterm's 16-bit `rgb:RRRR/GGGG/BBBB` reply form (`c * 257`).
 */
export type TerminalTheme = { fg: [number, number, number], bg: [number, number, number], };
