/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/cards/{card_id}/codex": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_codex"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{card_id}/terminal": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Look up the Terminal row a card owns. Returns 404 if the card has no
         *     terminal (yet). The UI uses this to validate a card_id cached in
         *     localStorage before attempting a WS attach to its terminal.
         */
        get: operations["get_terminal_for_card"];
        put?: never;
        post: operations["create_terminal"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/cards/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_card"];
        options?: never;
        head?: never;
        patch: operations["update_card"];
        trace?: never;
    };
    "/api/coves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_coves"];
        put?: never;
        post: operations["create_cove"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coves/{cove_id}/waves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_waves_by_cove"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/coves/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["delete_cove"];
        options?: never;
        head?: never;
        patch: operations["update_cove"];
        trace?: never;
    };
    "/api/overlays": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_overlays"];
        put?: never;
        post: operations["upsert_overlay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/overlays/delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["delete_overlay"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_plugins"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/install": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["install_plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/views": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_plugin_views"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_plugin_detail"];
        put?: never;
        post?: never;
        delete: operations["uninstall_plugin"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["patch_plugin_config"];
        trace?: never;
    };
    "/api/plugins/{id}/disable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["disable_plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/enable": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["enable_plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/log": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["tail_plugin_log"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/reload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["reload_plugin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/resources/{view_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_plugin_view_html"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/rotate-token": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["rotate_plugin_token"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/plugins/{id}/tool-call": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["plugin_tool_call"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waves": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["create_wave"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/waves/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["get_wave_detail"];
        put?: never;
        post?: never;
        delete: operations["delete_wave"];
        options?: never;
        head?: never;
        patch: operations["update_wave"];
        trace?: never;
    };
    "/api/waves/{wave_id}/cards": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["list_cards_by_wave"];
        put?: never;
        post: operations["create_card"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Card: {
            /** Format: int64 */
            created_at: number;
            id: string;
            /**
             * @description `"terminal"` for built-in PTY cards, `"plugin:<plugin-id>:<view-id>"`
             *     for plugin-provided cards. Kernel never interprets beyond that prefix.
             */
            kind: string;
            /**
             * @description Opaque JSON blob — ts-rs would otherwise emit `unknown` via the
             *     `serde-json-impl` feature, but we pin it explicitly so a future
             *     feature-flag change can't silently widen / narrow the surface.
             */
            payload: Record<string, never>;
            /** Format: double */
            sort: number;
            /** Format: int64 */
            updated_at: number;
            wave_id: string;
        };
        CardPatch: {
            kind?: string | null;
            payload?: Record<string, never> | null;
            /** Format: double */
            sort?: number | null;
        };
        Cove: {
            color: string;
            /** Format: int64 */
            created_at: number;
            id: string;
            name: string;
            /** Format: double */
            sort: number;
            /** Format: int64 */
            updated_at: number;
        };
        CovePatch: {
            color?: string | null;
            name?: string | null;
            /** Format: double */
            sort?: number | null;
        };
        /**
         * @description Body payload accepted by `POST /api/waves/:wave_id/cards`.
         *
         *     Two mutually-exclusive paths:
         *       * **Direct create** — `kind`, `sort`, `payload`, `title` set (legacy
         *         pre-M2 wire). The kernel writes the row verbatim.
         *       * **`via_tool_call`** — kernel invokes the plugin's tool, extracts the
         *         `ui://` resource URI from `_meta.ui.resourceUri`, persists a Card with
         *         `kind = <resource_uri>` and `payload = structuredContent`.
         *
         *     When both are sent, `via_tool_call` wins. Documented in this module's
         *     header. We keep the legacy fields alongside via `#[serde(flatten)]` so
         *     existing clients (web-calm AddPanel for terminal/doc cards) keep working
         *     unchanged.
         */
        CreateCardBody: {
            /**
             * @description Legacy direct-create fields. Mirrors `NewCard` shape; `wave_id` is
             *     taken from the path so we omit it here.
             */
            kind?: string | null;
            payload?: Record<string, never> | null;
            /** Format: double */
            sort?: number | null;
            via_tool_call?: null | components["schemas"]["ViaToolCall"];
        };
        /**
         * @description JSON shape returned for every error response — `{error, code}`.
         *     Mirrors the body produced by `CalmError::into_response`. Hand-written
         *     duplicate of the in-line `json!` body so OpenAPI consumers see a
         *     concrete schema.
         */
        ErrorBody: {
            /**
             * @description Stable machine-readable code — one of `not_found`, `conflict`,
             *     `bad_request`, `unauthorized`, `plugin_install`, `plugin_permission`,
             *     `plugin_conflict`, `db_error`, `io_error`, `serde_error`, `internal`,
             *     `forbidden_tool`, `not_a_card_tool`, `tool_call_failed`.
             */
            code: string;
            /** @description Human-readable error message. */
            error: string;
        };
        InstallBody: {
            source: components["schemas"]["InstallSource"];
        };
        InstallSource: {
            /** @enum {string} */
            kind: "local_path";
            path: string;
        } | {
            /** @enum {string} */
            kind: "other";
        };
        NewCard: {
            kind: string;
            payload?: Record<string, never>;
            /** Format: double */
            sort?: number | null;
            /**
             * @description Defaulted so the REST handler can override from the `:wave_id` path
             *     param without forcing every client body to repeat it. Direct repo
             *     callers must still set this — passing "" produces a NotFound.
             */
            wave_id?: string;
        };
        NewCodexBody: {
            /** @description Working directory codex runs in. Defaults to `$HOME` if empty. */
            cwd?: string | null;
            /**
             * @description Required — the first user prompt. Codex's `exec` flow accepts it
             *     as a positional arg.
             */
            initial_prompt: string;
            /** @description Optional override (default codex picks per its own config). */
            model?: string | null;
            /**
             * @description Reserved for a future codex permission/sandbox flag — not wired
             *     yet (the right `-c` config keys for `approval_policy` / sandbox
             *     are version-sensitive). We accept the field so the schema-form on
             *     the frontend can collect it without errors.
             */
            permission_mode?: string | null;
        };
        NewCove: {
            color: string;
            name: string;
            /**
             * Format: double
             * @description If absent, server appends to end.
             */
            sort?: number | null;
        };
        NewOverlay: {
            entity_id: string;
            entity_kind: string;
            kind: string;
            payload: Record<string, never>;
            plugin_id: string;
        };
        NewTerminalBody: {
            /** @description Empty string or missing → `$HOME` (then cwd of server). */
            cwd?: string;
            /** @description Extra env on top of the inherited set. JSON object: `{"FOO":"bar"}`. */
            env?: Record<string, never>;
            /** @description Empty string or missing → `$SHELL` (then `/bin/sh`). */
            program?: string;
        };
        NewWave: {
            cove_id: string;
            /** Format: double */
            sort?: number | null;
            title: string;
        };
        Overlay: {
            entity_id: string;
            /** @description `"wave"` or `"card"`. */
            entity_kind: string;
            id: string;
            /** @description Plugin-defined string. Kernel does not interpret. */
            kind: string;
            /**
             * @description Opaque JSON blob — see `Card.payload` for the rationale on the
             *     explicit `unknown` override.
             */
            payload: Record<string, never>;
            plugin_id: string;
            /** Format: int64 */
            updated_at: number;
        };
        OverlayDeleteBody: {
            entity_id: string;
            entity_kind: string;
            kind: string;
            plugin_id: string;
        };
        OverlayQuery: {
            /**
             * @description Optional. When omitted, returns every overlay of `entity_kind`
             *     across the workspace — the sidebar uses this form to render
             *     accurate per-wave status without fetching each wave's detail.
             */
            entity_id?: string | null;
            entity_kind: string;
        };
        Plugin: {
            enabled: boolean;
            id: string;
            install_path: string;
            /** Format: int64 */
            installed_at: number;
            manifest: Record<string, never>;
            /** Format: int64 */
            updated_at: number;
            user_config: Record<string, never>;
            version: string;
        };
        /**
         * @description Single-plugin detail returned by GET-by-id, install, enable, disable,
         *     config-patch, and reload. The full manifest blob rides along so the UI can
         *     render version/author/views without a separate fetch.
         */
        PluginDetail: {
            enabled: boolean;
            id: string;
            /** Format: int64 */
            installed_at: number;
            last_error?: string | null;
            manifest: Record<string, never>;
            state: string;
            /** Format: int64 */
            updated_at: number;
            user_config: Record<string, never>;
            version: string;
        };
        /**
         * @description Compact row used by `GET /api/plugins`. Pairs the persisted `Plugin` row
         *     with the runtime status the supervisor knows about. The full manifest is
         *     excluded here to keep the list payload cheap; callers needing the manifest
         *     hit `GET /api/plugins/:id`.
         */
        PluginListItem: {
            enabled: boolean;
            id: string;
            last_error?: string | null;
            manifest_description?: string | null;
            manifest_name: string;
            /**
             * @description Wire-name string per design §7.1: `running | spawning | crashed |
             *     disabled | installing | installed`.
             */
            state: string;
            version: string;
        };
        Terminal: {
            card_id: string;
            /** Format: int64 */
            created_at: number;
            cwd: string;
            daemon_handle?: string | null;
            env: Record<string, never>;
            id: string;
            program: string;
        };
        /**
         * @description M5: AppBridge → kernel tool-call wire body. Mirrors the JSON-RPC
         *     `tools/call` params shape so the web-calm helper can hand it through
         *     verbatim from the iframe-side `app.callServerTool({ name, arguments })`.
         */
        ToolCallBody: {
            arguments?: Record<string, never>;
            name: string;
        };
        ViaToolCall: {
            arguments?: Record<string, never>;
            plugin_id: string;
            tool_name: string;
        };
        /**
         * @description One entry in the `/api/plugins/views` catalog. Used by Slice G's AddPanel.
         *
         *     M3 (mcp-apps migration) adds `resource_uri` as the canonical
         *     `ui://<plugin>/<view>` identifier. `plugin_id` + `view_id` stay on the
         *     wire alongside it during the M3→M4 transition; M4's frontend pivots to
         *     `resource_uri` and a follow-up slice may drop the legacy pair.
         */
        ViewCatalogEntry: {
            default_size?: null | components["schemas"]["ViewSizeWire"];
            icon?: string | null;
            plugin_id: string;
            /**
             * @description Canonical MCP Apps URI: `ui://<plugin_id>/<view_id>`. Always present —
             *     computed kernel-side so the frontend doesn't have to redo the join.
             */
            resource_uri: string;
            /** @description `"card"` for M3 — wave/cove are banned per design §10. */
            scope: string;
            title: string;
            view_id: string;
        };
        ViewSizeWire: {
            /** Format: int32 */
            h: number;
            /** Format: int32 */
            min_h?: number | null;
            /** Format: int32 */
            min_w?: number | null;
            /** Format: int32 */
            w: number;
        };
        Wave: {
            /** Format: int64 */
            archived_at?: number | null;
            cove_id: string;
            /** Format: int64 */
            created_at: number;
            id: string;
            /** Format: double */
            sort: number;
            title: string;
            /** Format: int64 */
            updated_at: number;
        };
        /**
         * @description What a Wave detail page renders: the wave itself plus its cards and
         *     any overlays scoped to the wave (status/progress badges) and its cards.
         */
        WaveDetail: {
            cards: components["schemas"]["Card"][];
            overlays: components["schemas"]["Overlay"][];
            wave: components["schemas"]["Wave"];
        };
        WavePatch: {
            /**
             * Format: int64
             * @description Pass `Some(Some(ts))` to archive, `Some(None)` to unarchive,
             *     or omit (`None`) to leave alone.
             */
            archived_at?: number | null;
            /** Format: double */
            sort?: number | null;
            title?: string | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    create_codex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card id (must be a codex card) */
                card_id: string;
            };
            cookie?: never;
        };
        /** @description Codex spawn parameters */
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewCodexBody"];
            };
        };
        responses: {
            /** @description Codex spawned; hook events stream over WS */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Card is not a codex card */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Spawn failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_terminal_for_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card id (must be a terminal card) */
                card_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Terminal row for this card */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Terminal"];
                };
            };
            /** @description Card has no terminal yet */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_terminal: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card id (must be a terminal card) */
                card_id: string;
            };
            cookie?: never;
        };
        /** @description Optional body — empty means use defaults */
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewTerminalBody"];
            };
        };
        responses: {
            /** @description Terminal created and daemon spawned */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Terminal"];
                };
            };
            /** @description Card is not a terminal card */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Daemon spawn failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Card deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Card id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CardPatch"];
            };
        };
        responses: {
            /** @description Card updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Card not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_coves: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description List all coves */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cove"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_cove: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewCove"];
            };
        };
        responses: {
            /** @description Cove created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cove"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_waves_by_cove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cove id */
                cove_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Waves under cove */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wave"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_cove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cove id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cove deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Cove not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_cove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Cove id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CovePatch"];
            };
        };
        responses: {
            /** @description Cove updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Cove"];
                };
            };
            /** @description Cove not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_overlays: {
        parameters: {
            query: {
                entity_kind: string;
                /**
                 * @description Optional. When omitted, returns every overlay of `entity_kind`
                 *     across the workspace — the sidebar uses this form to render
                 *     accurate per-wave status without fetching each wave's detail.
                 */
                entity_id?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Overlays for an entity (or all of a kind when entity_id is omitted) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overlay"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    upsert_overlay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewOverlay"];
            };
        };
        responses: {
            /** @description Overlay upserted */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Overlay"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_overlay: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OverlayDeleteBody"];
            };
        };
        responses: {
            /** @description Overlay deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_plugins: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Installed plugins with their runtime state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginListItem"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    install_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstallBody"];
            };
        };
        responses: {
            /** @description Plugin installed (disabled by default) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Manifest invalid / unsupported source */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin id already installed */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_plugin_views: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Catalog of views from currently enabled plugins */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ViewCatalogEntry"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_plugin_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin detail (manifest + state) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    uninstall_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin uninstalled */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    patch_plugin_config: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        /** @description Free-form user-config JSON object */
        requestBody: {
            content: {
                "application/json": Record<string, never>;
            };
        };
        responses: {
            /** @description Config updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    disable_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin disabled and stopped */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Stop failed / internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    enable_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Plugin enabled and spawned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Spawn failed / internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    tail_plugin_log: {
        parameters: {
            query?: {
                n?: number | null;
            };
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Recent stderr lines (newest last) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": string[];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    reload_plugin: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Manifest reloaded + plugin restarted if enabled */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Manifest invalid / id mismatch after reload */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_plugin_view_html: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
                /** @description View id within the plugin manifest */
                view_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description MCP-App HTML (Content-Type: text/html;profile=mcp-app) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html;profile=mcp-app": string;
                };
            };
            /** @description Malformed ui:// URI */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin or view not found / asset missing */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description I/O error reading asset */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    rotate_plugin_token: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Token rotated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PluginDetail"];
                };
            };
            /** @description Plugin not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Rotate failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    plugin_tool_call: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Plugin id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ToolCallBody"];
            };
        };
        responses: {
            /** @description Tool result JSON (shape depends on dispatched neige.* callback) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            /** @description Non-neige.* tool requested from iframe */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin not running */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_wave: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewWave"];
            };
        };
        responses: {
            /** @description Wave created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wave"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    get_wave_detail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wave detail (wave + its cards + overlays) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WaveDetail"];
                };
            };
            /** @description Wave not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    delete_wave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id */
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Wave deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Wave not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    update_wave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id */
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["WavePatch"];
            };
        };
        responses: {
            /** @description Wave updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Wave"];
                };
            };
            /** @description Wave not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    list_cards_by_wave: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id */
                wave_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cards in wave (sorted) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"][];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
    create_card: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Wave id this card belongs to */
                wave_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateCardBody"];
            };
        };
        responses: {
            /** @description Card created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Card"];
                };
            };
            /** @description Missing `kind` and no `via_tool_call` */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin lacks `permissions.cards_create` */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin not running / not in registry */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Tool returned no `_meta.ui.resourceUri` */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Internal error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
            /** @description Plugin tool call failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorBody"];
                };
            };
        };
    };
}
