//! Shared host gate process machinery. Admission and completion belong to adapters.
use super::task_verify_adapter::{GateStep, GateVerdict};
use crate::error::{CalmError, Result};
use serde_json::Value;
use std::path::Path;
const LOG_TAIL_BYTES: u64 = 8 * 1024;
/// Extra margin beyond the tail for the `::gate-step` sentinel scan; a step that alone prints >64KiB after its sentinel loses attribution (`failing_step: None`), acceptable for an advisory field.
const LOG_SENTINEL_MARGIN_BYTES: u64 = 64 * 1024;
/// POSIX single-quote escaping: `'` → `'\''`.
fn sh_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// First action is the release handshake (kernel death before release EOFs the pipe and the held child exits 75 having executed nothing);
/// the exit code is written via tmp + `rename(2)` last, the exit path is `unset` before any step runs, and each step runs in a subshell so a top-level `exit`/`exec`/`set -e` ends the STEP, never bypasses the finish handler.
pub(crate) fn render_gate_wrapper(steps: &[GateStep]) -> String {
    let mut script = String::new();
    script.push_str("#!/bin/sh\n");
    script.push_str("# generated by neige-calm task-verify; do not edit\n");
    script.push_str("read -r _go || exit 75\n");
    script.push_str("neige_gate_exit_path=$NEIGE_GATE_EXIT_PATH\n");
    script.push_str("unset NEIGE_GATE_EXIT_PATH\n");
    script.push_str("neige_gate_finish() {\n");
    script.push_str(
        "  printf '%s\\n' \"$1\" > \"$neige_gate_exit_path.tmp\" && \
         mv -f -- \"$neige_gate_exit_path.tmp\" \"$neige_gate_exit_path\"\n",
    );
    script.push_str("  exit \"$1\"\n");
    script.push_str("}\n");
    for step in steps {
        script.push_str(&format!(
            "printf '%s\\n' {}\n",
            sh_single_quote(&format!("::gate-step {}", step.name))
        ));
        script.push_str("(\n");
        script.push_str(&step.cmd);
        script.push('\n');
        script.push_str(")\n");
        script.push_str("neige_gate_rc=$?\n");
        script.push_str(
            "if [ \"$neige_gate_rc\" -ne 0 ]; then neige_gate_finish \"$neige_gate_rc\"; fi\n",
        );
    }
    script.push_str("neige_gate_finish 0\n");
    script
}

/// Last `::gate-step <name>` sentinel in the log, if any.
fn last_gate_step_sentinel(log_text: &str) -> Option<String> {
    log_text
        .lines()
        .filter_map(|line| line.strip_prefix("::gate-step "))
        .next_back()
        .map(|s| s.trim().to_string())
}

pub(crate) fn read_log_tail(log_path: &Path) -> (String, Option<String>) {
    use std::io::{Read, Seek, SeekFrom};
    let Ok(mut file) = std::fs::File::open(log_path) else {
        return (String::new(), None);
    };
    let len = file.metadata().map(|m| m.len()).unwrap_or(0);
    let window_start = len.saturating_sub(LOG_TAIL_BYTES + LOG_SENTINEL_MARGIN_BYTES);
    if file.seek(SeekFrom::Start(window_start)).is_err() {
        return (String::new(), None);
    }
    let mut bytes = Vec::new();
    if file.read_to_end(&mut bytes).is_err() {
        return (String::new(), None);
    }
    let text = String::from_utf8_lossy(&bytes);
    let sentinel = last_gate_step_sentinel(&text);
    let tail_start = bytes.len().saturating_sub(LOG_TAIL_BYTES as usize);
    let tail = String::from_utf8_lossy(&bytes[tail_start..]).to_string();
    (tail, sentinel)
}

/// The wrapper-written exit file is consulted ONLY for dead work (a same-user worker can forge it); `Err(())` = present but unparseable, a foreign artifact, fail loudly.
pub(crate) fn read_exit_file(exit_path: &Path) -> std::result::Result<Option<i32>, ()> {
    match std::fs::read_to_string(exit_path) {
        Ok(content) => content.trim().parse::<i32>().map(Some).map_err(|_| ()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        // Unreadable-but-present is indistinguishable from foreign.
        Err(_) => Err(()),
    }
}

/// From the live wait status, or — for dead recovered work only — the exit file's value.
pub(crate) fn verdict_from_exit_code(exit_code: i32, log_path: &Path, attempt: i64) -> GateVerdict {
    let (log_tail, sentinel) = read_log_tail(log_path);
    if exit_code == 0 {
        return GateVerdict {
            passed: true,
            status_detail: None,
            failing_step: None,
            exit_code: Some(0),
            log_tail,
            log_path: log_path.display().to_string(),
            attempt,
        };
    }
    // No `::gate-step` sentinel means no step ever ran (e.g. the handshake `read` hit EOF → exit 75) → infra, not red.
    let status_detail = if sentinel.is_some() {
        "gate-red"
    } else {
        "gate-infra"
    };
    GateVerdict {
        passed: false,
        status_detail: Some(status_detail.into()),
        failing_step: sentinel,
        exit_code: Some(exit_code),
        log_tail,
        log_path: log_path.display().to_string(),
        attempt,
    }
}

pub(crate) fn infra_verdict(reason: &str, log_path: &Path, attempt: i64) -> GateVerdict {
    let (mut log_tail, sentinel) = read_log_tail(log_path);
    if log_tail.is_empty() {
        log_tail = reason.to_string();
    }
    GateVerdict {
        passed: false,
        status_detail: Some("gate-infra".into()),
        failing_step: sentinel,
        exit_code: None,
        log_tail,
        log_path: log_path.display().to_string(),
        attempt,
    }
}

pub(crate) fn timeout_verdict(log_path: &Path, attempt: i64, timeout_secs: i64) -> GateVerdict {
    let (mut log_tail, sentinel) = read_log_tail(log_path);
    if log_tail.is_empty() {
        log_tail = format!("gate timed out after {timeout_secs}s");
    }
    GateVerdict {
        passed: false,
        status_detail: Some("gate-timeout".into()),
        failing_step: sentinel,
        exit_code: None,
        log_tail,
        log_path: log_path.display().to_string(),
        attempt,
    }
}

pub(crate) async fn spawn_held(
    repo: &dyn crate::db::RouteRepo,
    cwd: &Path,
    steps: &[GateStep],
    script_path: &Path,
    log_path: &Path,
    exit_path: &Path,
) -> Result<tokio::process::Child> {
    if !cwd.is_dir() {
        return Err(CalmError::BadRequest(format!(
            "gate cwd {} does not exist",
            cwd.display()
        )));
    }
    tokio::fs::write(script_path, render_gate_wrapper(steps)).await?;
    let log_file = std::fs::File::create(log_path)?;
    let log_file_err = log_file.try_clone()?;
    let mut cmd = tokio::process::Command::new("/bin/sh");
    cmd.arg(script_path)
        .current_dir(cwd)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::from(log_file))
        .stderr(std::process::Stdio::from(log_file_err))
        // Start from an EMPTY environment: no `NEIGE_MCP_SOCKET`/`NEIGE_MCP_TOKEN` (the gate cannot write kernel state) and no incidental kernel secrets.
        .env_clear()
        .env("NEIGE_GATE_EXIT_PATH", exit_path);
    // Deliberately NO `kill_on_drop`: a graceful kernel shutdown drops the observer and must leave the gate RUNNING so boot recovery can reattach.
    // `kill_on_drop` would SIGKILL only the `/bin/sh` wrapper, never its group; every kernel-side kill targets the recorded process GROUP instead.
    for key in ["PATH", "HOME", "LANG", "LC_ALL", "TERM"] {
        if let Some(v) = std::env::var_os(key) {
            cmd.env(key, v);
        }
    }
    if let Value::Object(env) = super::terminal_adapter::terminal_worker_env(repo)
        .await
        .unwrap_or(Value::Null)
    {
        for (k, v) in env {
            if let Value::String(v) = v {
                cmd.env(k, v);
            }
        }
    }
    // One process group = one kill target for wrapper + current
    // step + descendants.
    // SAFETY: setsid() is async-signal-safe and called in the
    // forked child before exec.
    unsafe {
        cmd.pre_exec(|| {
            if libc::setsid() == -1 {
                return Err(std::io::Error::last_os_error());
            }
            Ok(())
        });
    }
    let child = cmd.spawn()?;
    Ok(child)
}

/// A kernel-observed verdict whose unreaped leader still fences recovery.
/// Keep this value through candidate terminal settlement, then explicitly reap.
pub(crate) struct GateObservation {
    child: tokio::process::Child,
    pub verdict: GateVerdict,
}
impl GateObservation {
    pub async fn reap(mut self) {
        let _ = self.child.wait().await;
    }
}

pub(crate) async fn wait_verdict(
    child: tokio::process::Child,
    artifacts: super::SpawnArtifacts,
    log: std::path::PathBuf,
    attempt: i64,
    timeout_secs: i64,
) -> GateVerdict {
    let observation = observe_verdict(child, artifacts, log, attempt, timeout_secs).await;
    let verdict = observation.verdict.clone();
    observation.reap().await;
    verdict
}

/// Observe actual kernel status without releasing the leader's identity.
pub(crate) async fn observe_verdict(
    child: tokio::process::Child,
    artifacts: super::SpawnArtifacts,
    log: std::path::PathBuf,
    attempt: i64,
    timeout_secs: i64,
) -> GateObservation {
    use std::time::Duration;
    // Do not poll Child::wait/try_wait until group cleanup: Tokio reaps on poll/drop, losing the leader identity; WNOWAIT keeps the zombie leader owned until we signal.
    #[cfg(target_os = "linux")]
    let wait = tokio::time::timeout(Duration::from_secs(timeout_secs as u64), async {
        loop {
            let mut info: libc::siginfo_t = unsafe { std::mem::zeroed() };
            // SAFETY: valid output pointer; this observes our retained Child only.
            let rc = unsafe {
                libc::waitid(
                    libc::P_PID,
                    artifacts.pid as libc::id_t,
                    &mut info,
                    libc::WEXITED | libc::WNOHANG | libc::WNOWAIT,
                )
            };
            if rc != 0 {
                let error = std::io::Error::last_os_error();
                if error.kind() != std::io::ErrorKind::Interrupted {
                    return Err(error);
                }
            } else if unsafe { info.si_pid() } != 0 {
                // si_status is a real wait result, not wrapper file evidence.
                return Ok(if info.si_code == libc::CLD_EXITED {
                    Some(unsafe { info.si_status() })
                } else {
                    None
                });
            }
            tokio::time::sleep(Duration::from_millis(20)).await;
        }
    })
    .await;
    #[cfg(not(target_os = "linux"))]
    let mut child = child;
    #[cfg(not(target_os = "linux"))]
    let wait = tokio::time::timeout(Duration::from_secs(timeout_secs as u64), async {
        child.wait().await.map(|status| status.code())
    })
    .await;
    kill(&artifacts);
    // A signal being delivered is not proof of stop; keep the leader until descendants have stopped.
    let cleanup = wait_group_stopped(&artifacts).await;
    if let Err(error) = cleanup {
        tracing::warn!(%error, "gate group cleanup remains unresolved; preserving actual wait evidence");
    }
    let verdict = match wait {
        Err(_) => timeout_verdict(&log, attempt, timeout_secs),
        Ok(Err(error)) => {
            infra_verdict(&format!("gate wrapper wait failed: {error}"), &log, attempt)
        }
        Ok(Ok(Some(code))) => verdict_from_exit_code(code, &log, attempt),
        Ok(Ok(None)) => infra_verdict("gate wrapper killed by signal", &log, attempt),
    };
    GateObservation { child, verdict }
}

/// Never infer cleanup from a missing leader or signal an unauthenticated PGID; inability to inspect the group fails closed.
pub(crate) fn group_stopped(artifacts: &super::SpawnArtifacts) -> Result<bool> {
    let boot = crate::proc_identity::read_boot_id()
        .ok_or_else(|| CalmError::Conflict("gate cleanup boot identity unavailable".into()))?;
    if boot != artifacts.boot_id {
        return Ok(true);
    }
    if artifacts.pgid <= 1 {
        return Err(CalmError::Conflict(
            "gate cleanup group identity invalid".into(),
        ));
    }
    for entry in std::fs::read_dir("/proc")? {
        let entry = entry?;
        if entry.file_name().to_string_lossy().parse::<i32>().is_err() {
            continue;
        }
        let stat = match std::fs::read_to_string(entry.path().join("stat")) {
            Ok(stat) => stat,
            Err(error) if error.kind() == std::io::ErrorKind::NotFound => continue,
            Err(error) => return Err(error.into()),
        };
        let fields = crate::proc_identity::parse_proc_stat_fields(&stat).ok_or_else(|| {
            CalmError::Conflict("gate cleanup process identity unreadable".into())
        })?;
        if fields.pgrp == artifacts.pgid && fields.state != 'Z' && fields.state != 'X' {
            return Ok(false);
        }
    }
    Ok(true)
}

pub(crate) async fn wait_group_stopped(artifacts: &super::SpawnArtifacts) -> Result<()> {
    tokio::time::timeout(std::time::Duration::from_secs(5), async {
        while !group_stopped(artifacts)? {
            tokio::time::sleep(std::time::Duration::from_millis(20)).await;
        }
        Ok(())
    })
    .await
    .map_err(|_| CalmError::Conflict("gate process-group cleanup remains unresolved".into()))?
}

pub(crate) fn kill(artifacts: &super::SpawnArtifacts) {
    if crate::proc_identity::verify_owned_pid(
        artifacts.pid,
        artifacts.start_time,
        &artifacts.boot_id,
    ) {
        crate::proc_identity::signal_process_group(artifacts.pgid, libc::SIGKILL);
    }
}
