//! Shared host gate process machinery. Admission and completion belong to adapters.
use super::task_verify_adapter::{GateStep, GateVerdict};
use crate::error::{CalmError, Result};
use serde_json::Value;
use std::path::Path;
const LOG_TAIL_BYTES: u64 = 8 * 1024;
/// Extra margin beyond the tail for the `::gate-step` sentinel scan; a step that alone prints >64KiB after its sentinel loses attribution (`failing_step: None`), acceptable for an advisory field.
const LOG_SENTINEL_MARGIN_BYTES: u64 = 64 * 1024;
/// POSIX single-quote escaping: `'` → `'\''`.
fn sh_single_quote(s: &str) -> String {
    format!("'{}'", s.replace('\'', "'\\''"))
}

/// First action is the release handshake (kernel death before release EOFs the pipe and the held child exits 75 having executed nothing);
/// the exit code is written via tmp + `rename(2)` last, the exit path is `unset` before any step runs, and each step runs in a subshell so a top-level `exit`/`exec`/`set -e` ends the STEP, never bypasses the finish handler.
pub(crate) fn render_gate_wrapper(steps: &[GateStep]) -> String {
    let mut script = String::new();
    script.push_str("#!/bin/sh\n");
    script.push_str("# generated by neige-calm task-verify; do not edit\n");
    script.push_str("read -r _go || exit 75\n");
    script.push_str("neige_gate_exit_path=$NEIGE_GATE_EXIT_PATH\n");
    script.push_str("unset NEIGE_GATE_EXIT_PATH\n");
    script.push_str("neige_gate_finish() {\n");
    script.push_str(
        "  printf '%s\\n' \"$1\" > \"$neige_gate_exit_path.tmp\" && \
         mv -f -- \"$neige_gate_exit_path.tmp\" \"$neige_gate_exit_path\"\n",
    );
    script.push_str("  exit \"$1\"\n");
    script.push_str("}\n");
    for step in steps {
        script.push_str(&format!(
            "printf '%s\\n' {}\n",
            sh_single_quote(&format!("::gate-step {}", step.name))
        ));
        script.push_str("(\n");
        script.push_str(&step.cmd);
        script.push('\n');
        script.push_str(")\n");
        script.push_str("neige_gate_rc=$?\n");
        script.push_str(
            "if [ \"$neige_gate_rc\" -ne 0 ]; then neige_gate_finish \"$neige_gate_rc\"; fi\n",
        );
    }
    script.push_str("neige_gate_finish 0\n");
    script
}

/// Last `::gate-step <name>` sentinel in the log, if any.
fn last_gate_step_sentinel(log_text: &str) -> Option<String> {
    log_text
        .lines()
        .filter_map(|line| line.strip_prefix("::gate-step "))
        .next_back()
        .map(|s| s.trim().to_string())
}

pub(crate) fn read_log_tail(log_path: &Path) -> (String, Option<String>) {
    use std::io::{Read, Seek, SeekFrom};
    let Ok(mut file) = std::fs::File::open(log_path) else {
        return (String::new(), None);
    };
    let len = file.metadata().map(|m| m.len()).unwrap_or(0);
    let window_start = len.saturating_sub(LOG_TAIL_BYTES + LOG_SENTINEL_MARGIN_BYTES);
    if file.seek(SeekFrom::Start(window_start)).is_err() {
        return (String::new(), None);
    }
    let mut bytes = Vec::new();
    if file.read_to_end(&mut bytes).is_err() {
        return (String::new(), None);
    }
    let text = String::from_utf8_lossy(&bytes);
    let sentinel = last_gate_step_sentinel(&text);
    let tail_start = bytes.len().saturating_sub(LOG_TAIL_BYTES as usize);
    let tail = String::from_utf8_lossy(&bytes[tail_start..]).to_string();
    (tail, sentinel)
}

/// The wrapper-written exit file is consulted ONLY for dead work (a same-user worker can forge it); `Err(())` = present but unparseable, a foreign artifact, fail loudly.
pub(crate) fn read_exit_file(exit_path: &Path) -> std::result::Result<Option<i32>, ()> {
    match std::fs::read_to_string(exit_path) {
        Ok(content) => content.trim().parse::<i32>().map(Some).map_err(|_| ()),
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => Ok(None),
        // Unreadable-but-present is indistinguishable from foreign.
        Err(_) => Err(()),
    }
}

/// From the live wait status, or — for dead recovered work only — the exit file's value.
pub(crate) fn verdict_from_exit_code(exit_code: i32, log_path: &Path, attempt: i64) -> GateVerdict {
    let (log_tail, sentinel) = read_log_tail(log_path);
    if exit_code == 0 {
        return GateVerdict {
            passed: true,
            status_detail: None,
            failing_step: None,
            exit_code: Some(0),
            log_tail,
            log_path: log_path.display().to_string(),
            attempt,
        };
    }
    // No `::gate-step` sentinel means no step ever ran (e.g. the handshake `read` hit EOF → exit 75) → infra, not red.
    let status_detail = if sentinel.is_some() {
        "gate-red"
    } else {
        "gate-infra"
    };
    GateVerdict {
        passed: false,
        status_detail: Some(status_detail.into()),
        failing_step: sentinel,
        exit_code: Some(exit_code),
        log_tail,
        log_path: log_path.display().to_string(),
        attempt,
    }
}

pub(crate) fn infra_verdict(reason: &str, log_path: &Path, attempt: i64) -> GateVerdict {
    let (mut log_tail, sentinel) = read_log_tail(log_path);
    if log_tail.is_empty() {
        log_tail = reason.to_string();
    }
    GateVerdict {
        passed: false,
        status_detail: Some("gate-infra".into()),
        failing_step: sentinel,
        exit_code: None,
        log_tail,
        log_path: log_path.display().to_string(),
        attempt,
    }
}

pub(crate) fn timeout_verdict(log_path: &Path, attempt: i64, timeout_secs: i64) -> GateVerdict {
    let (mut log_tail, sentinel) = read_log_tail(log_path);
    if log_tail.is_empty() {
        log_tail = format!("gate timed out after {timeout_secs}s");
    }
    GateVerdict {
        passed: false,
        status_detail: Some("gate-timeout".into()),
        failing_step: sentinel,
        exit_code: None,
        log_tail,
        log_path: log_path.display().to_string(),
        attempt,
    }
}

pub(crate) async fn spawn_held(
    repo: &dyn crate::db::RouteRepo,
    cwd: &Path,
    steps: &[GateStep],
    script_path: &Path,
    log_path: &Path,
    exit_path: &Path,
    op_marker: &str,
) -> Result<tokio::process::Child> {
    if !cwd.is_dir() {
        return Err(CalmError::BadRequest(format!(
            "gate cwd {} does not exist",
            cwd.display()
        )));
    }
    tokio::fs::write(script_path, render_gate_wrapper(steps)).await?;
    let log_file = std::fs::File::create(log_path)?;
    let log_file_err = log_file.try_clone()?;
    let mut cmd = tokio::process::Command::new("/bin/sh");
    cmd.arg(script_path)
        .current_dir(cwd)
        .stdin(std::process::Stdio::piped())
        .stdout(std::process::Stdio::from(log_file))
        .stderr(std::process::Stdio::from(log_file_err))
        // Start from an EMPTY environment: no `NEIGE_MCP_SOCKET`/`NEIGE_MCP_TOKEN` (the gate cannot write kernel state) and no incidental kernel secrets.
        .env_clear()
        .env("NEIGE_GATE_EXIT_PATH", exit_path)
        // Authenticates this gate's descendants to the recovery group sweep. UNLIKE `NEIGE_GATE_EXIT_PATH`
        // the wrapper does NOT `unset` it, so every descendant inherits it; a process that later recycles
        // the numeric pgid does not carry it. See `stop_group` / `group_members_with_env_marker`.
        .env("NEIGE_GATE_OP", op_marker);
    // Deliberately NO `kill_on_drop`: a graceful kernel shutdown drops the observer and must leave the gate RUNNING so boot recovery can reattach.
    // `kill_on_drop` would SIGKILL only the `/bin/sh` wrapper, never its group; every kernel-side kill targets the recorded process GROUP instead.
    for key in ["PATH", "HOME", "LANG", "LC_ALL", "TERM"] {
        if let Some(v) = std::env::var_os(key) {
            cmd.env(key, v);
        }
    }
    if let Value::Object(env) = super::terminal_adapter::terminal_worker_env(repo)
        .await
        .unwrap_or(Value::Null)
    {
        for (k, v) in env {
            if let Value::String(v) = v {
                cmd.env(k, v);
            }
        }
    }
    // One process group = one kill target for wrapper + current
    // step + descendants.
    // SAFETY: setsid() is async-signal-safe and called in the
    // forked child before exec.
    unsafe {
        cmd.pre_exec(|| {
            if libc::setsid() == -1 {
                return Err(std::io::Error::last_os_error());
            }
            Ok(())
        });
    }
    let child = cmd.spawn()?;
    Ok(child)
}

/// A kernel-observed verdict whose unreaped leader still fences recovery.
/// Keep this value through candidate terminal settlement, then explicitly reap.
pub(crate) struct GateObservation {
    child: tokio::process::Child,
    pub verdict: GateVerdict,
}
impl GateObservation {
    pub async fn reap(mut self) {
        let _ = self.child.wait().await;
    }
}

pub(crate) async fn wait_verdict(
    child: tokio::process::Child,
    artifacts: super::SpawnArtifacts,
    log: std::path::PathBuf,
    attempt: i64,
    timeout_secs: i64,
) -> GateVerdict {
    let observation = observe_verdict(child, artifacts, log, attempt, timeout_secs).await;
    let verdict = observation.verdict.clone();
    observation.reap().await;
    verdict
}

/// Observe actual kernel status without releasing the leader's identity.
pub(crate) async fn observe_verdict(
    child: tokio::process::Child,
    artifacts: super::SpawnArtifacts,
    log: std::path::PathBuf,
    attempt: i64,
    timeout_secs: i64,
) -> GateObservation {
    use std::time::Duration;
    // Do not poll Child::wait/try_wait until group cleanup: Tokio reaps on poll/drop, losing the leader identity; WNOWAIT keeps the zombie leader owned until we signal.
    #[cfg(target_os = "linux")]
    let wait = tokio::time::timeout(Duration::from_secs(timeout_secs as u64), async {
        loop {
            let mut info: libc::siginfo_t = unsafe { std::mem::zeroed() };
            // SAFETY: valid output pointer; this observes our retained Child only.
            let rc = unsafe {
                libc::waitid(
                    libc::P_PID,
                    artifacts.pid as libc::id_t,
                    &mut info,
                    libc::WEXITED | libc::WNOHANG | libc::WNOWAIT,
                )
            };
            if rc != 0 {
                let error = std::io::Error::last_os_error();
                if error.kind() != std::io::ErrorKind::Interrupted {
                    return Err(error);
                }
            } else if unsafe { info.si_pid() } != 0 {
                // si_status is a real wait result, not wrapper file evidence.
                return Ok(if info.si_code == libc::CLD_EXITED {
                    Some(unsafe { info.si_status() })
                } else {
                    None
                });
            }
            tokio::time::sleep(Duration::from_millis(20)).await;
        }
    })
    .await;
    #[cfg(not(target_os = "linux"))]
    let mut child = child;
    #[cfg(not(target_os = "linux"))]
    let wait = tokio::time::timeout(Duration::from_secs(timeout_secs as u64), async {
        child.wait().await.map(|status| status.code())
    })
    .await;
    kill(&artifacts);
    // A signal being delivered is not proof of stop; keep the leader until descendants have stopped.
    let cleanup = wait_group_stopped(&artifacts).await;
    if let Err(error) = cleanup {
        tracing::warn!(%error, "gate group cleanup remains unresolved; preserving actual wait evidence");
    }
    let verdict = match wait {
        Err(_) => timeout_verdict(&log, attempt, timeout_secs),
        Ok(Err(error)) => {
            infra_verdict(&format!("gate wrapper wait failed: {error}"), &log, attempt)
        }
        Ok(Ok(Some(code))) => verdict_from_exit_code(code, &log, attempt),
        Ok(Ok(None)) => infra_verdict("gate wrapper killed by signal", &log, attempt),
    };
    GateObservation { child, verdict }
}

/// Never infer cleanup from a missing leader or signal an unauthenticated PGID; inability to inspect the group fails closed.
pub(crate) fn group_stopped(artifacts: &super::SpawnArtifacts) -> Result<bool> {
    group_stopped_in(Path::new("/proc"), artifacts, |_| true)
}

pub(crate) async fn wait_group_stopped(artifacts: &super::SpawnArtifacts) -> Result<()> {
    tokio::time::timeout(std::time::Duration::from_secs(5), async {
        while !group_stopped(artifacts)? {
            tokio::time::sleep(std::time::Duration::from_millis(20)).await;
        }
        Ok(())
    })
    .await
    .map_err(|_| CalmError::Conflict("gate process-group cleanup remains unresolved".into()))?
}

/// Like [`group_stopped`], but a live member's classification comes from
/// [`crate::proc_identity::proc_env_marker`] against `NEIGE_GATE_OP=<op_marker>`. On the recovery
/// paths the wrapper's leader is dead and the numeric pgid can be reused by an unrelated process;
/// a proven-`Foreign` member (environ readable without the marker, or already gone) is NOT waited
/// for (nor swept), so a recycled pgid never turns a recovery into a 5 s timeout. Boot mismatch and
/// an invalid pgid are handled exactly as [`group_stopped`]. A live member whose environ is
/// UNREADABLE ([`crate::proc_identity::MarkerAuth::Unreadable`] — e.g. a same-uid descendant that
/// set `PR_SET_DUMPABLE=0`) is cleanup-uncertain, not proven foreign: it blocks the wait (fail
/// closed → the group never counts as stopped → `gate-infra`) yet is never killed (the sweep signals
/// only `Present`). An unparseable `stat` still returns `Err`.
pub(crate) fn marked_group_stopped(
    artifacts: &super::SpawnArtifacts,
    op_marker: &str,
) -> Result<bool> {
    group_stopped_in(Path::new("/proc"), artifacts, |pid| {
        marked_member_blocks(pid, op_marker)
    })
}

/// Fail closed on an unreadable live member: `Present` (proven ours) OR `Unreadable` (live but
/// environ hidden — cannot be proven foreign) both block the wait; only a proven-`Foreign` member
/// (readable without the marker, or already gone) is passed over.
fn marked_member_blocks(pid: i32, op_marker: &str) -> bool {
    match crate::proc_identity::proc_env_marker(pid, "NEIGE_GATE_OP", op_marker) {
        crate::proc_identity::MarkerAuth::Present
        | crate::proc_identity::MarkerAuth::Unreadable => true,
        crate::proc_identity::MarkerAuth::Foreign => false,
    }
}

/// One pass over `proc_root` (`/proc` in production): `Ok(false)` while a live (not `Z`/`X`)
/// process in the recorded pgid for which `blocks` holds is listed. Another boot's group is
/// stopped; an entry that vanished mid-scan (`ENOENT`/`ESRCH`) is skipped; an invalid pgid, an
/// unreadable listing, any other `stat` read error or an unparseable `stat` is `Err`.
fn group_stopped_in(
    proc_root: &Path,
    artifacts: &super::SpawnArtifacts,
    blocks: impl Fn(i32) -> bool,
) -> Result<bool> {
    let boot = crate::proc_identity::read_boot_id()
        .ok_or_else(|| CalmError::Conflict("gate cleanup boot identity unavailable".into()))?;
    if boot != artifacts.boot_id {
        return Ok(true);
    }
    if artifacts.pgid <= 1 {
        return Err(CalmError::Conflict(
            "gate cleanup group identity invalid".into(),
        ));
    }
    for entry in std::fs::read_dir(proc_root)? {
        let entry = entry?;
        let Ok(pid) = entry.file_name().to_string_lossy().parse::<i32>() else {
            continue;
        };
        let stat = match std::fs::read_to_string(entry.path().join("stat")) {
            Ok(stat) => stat,
            Err(error) if calm_worker_runtime::proc_entry_vanished(&error) => continue,
            Err(error) => return Err(error.into()),
        };
        let fields = crate::proc_identity::parse_proc_stat_fields(&stat).ok_or_else(|| {
            CalmError::Conflict("gate cleanup process identity unreadable".into())
        })?;
        if fields.pgrp == artifacts.pgid
            && fields.state != 'Z'
            && fields.state != 'X'
            && blocks(pid)
        {
            return Ok(false);
        }
    }
    Ok(true)
}

pub(crate) async fn wait_marked_group_stopped(
    artifacts: &super::SpawnArtifacts,
    op_marker: &str,
) -> Result<()> {
    tokio::time::timeout(std::time::Duration::from_secs(5), async {
        while !marked_group_stopped(artifacts, op_marker)? {
            tokio::time::sleep(std::time::Duration::from_millis(20)).await;
        }
        Ok(())
    })
    .await
    .map_err(|_| CalmError::Conflict("gate process-group cleanup remains unresolved".into()))?
}

pub(crate) fn kill(artifacts: &super::SpawnArtifacts) {
    if crate::proc_identity::verify_owned_pid(
        artifacts.pid,
        artifacts.start_time,
        &artifacts.boot_id,
    ) {
        crate::proc_identity::signal_process_group(artifacts.pgid, libc::SIGKILL);
    }
}

#[cfg(all(test, target_os = "linux"))]
mod tests {
    use super::{group_stopped_in, marked_member_blocks};
    use crate::operation::SpawnArtifacts;
    use calm_worker_runtime::test_support::{ChildGuard, ReapedProcDir};
    use std::os::unix::process::CommandExt as _;
    use std::process::Command;

    const MARKER: &str = "w:reaped#g1";

    fn artifacts(pgid: i32) -> SpawnArtifacts {
        SpawnArtifacts {
            pid: 2_000_000_003,
            pgid,
            start_time: 0,
            boot_id: crate::proc_identity::read_boot_id().expect("boot id"),
            log_path: None,
            extra: serde_json::json!({}),
        }
    }

    /// Any host process reaped between the `/proc` listing and the read of its `stat` fails that
    /// read with ESRCH, not ENOENT (#1793). The race is pinned without timing: a fake proc root
    /// entry resolves, through `/proc/self/fd`, to the held `/proc/<pid>` directory of a child that
    /// is already reaped, so reading its `stat` is ESRCH every time. Such an entry is not a live
    /// member of any group: both the plain and the marked stop predicates count the group stopped,
    /// and a live marked member listed beside it still holds the group running.
    #[test]
    fn a_process_reaped_mid_scan_is_not_a_cleanup_failure() {
        let reaped = ReapedProcDir::new();
        let live = ChildGuard::spawn(
            Command::new("sleep")
                .arg("300")
                .env("NEIGE_GATE_OP", MARKER)
                .process_group(0),
        );
        let live_pid = live.pid();
        // `spawn` can return while the child is still inside execve, when its environ reads empty
        // (so `Foreign`); the live-member case below needs the marker actually visible.
        let deadline = std::time::Instant::now() + std::time::Duration::from_secs(10);
        while crate::proc_identity::proc_env_marker(live_pid, "NEIGE_GATE_OP", MARKER)
            != crate::proc_identity::MarkerAuth::Present
        {
            assert!(
                std::time::Instant::now() < deadline,
                "the live sleeper's environ never showed the marker"
            );
            std::thread::sleep(std::time::Duration::from_millis(5));
        }

        let vanished_only = tempfile::tempdir().expect("tempdir");
        let with_live = tempfile::tempdir().expect("tempdir");
        for root in [vanished_only.path(), with_live.path()] {
            std::os::unix::fs::symlink(reaped.path(), root.join(reaped.pid.to_string()))
                .expect("symlink reaped");
        }
        std::os::unix::fs::symlink(
            format!("/proc/{live_pid}"),
            with_live.path().join(live_pid.to_string()),
        )
        .expect("symlink live");

        let read =
            std::fs::read_to_string(vanished_only.path().join(format!("{}/stat", reaped.pid)));
        assert_eq!(
            read.as_ref().map_err(std::io::Error::raw_os_error).err(),
            Some(Some(libc::ESRCH)),
            "the fixture must reproduce the reaped-mid-scan read: {read:?}"
        );
        let plain = group_stopped_in(vanished_only.path(), &artifacts(live_pid), |_| true);
        assert!(matches!(plain, Ok(true)), "{plain:?}");
        let marked = group_stopped_in(vanished_only.path(), &artifacts(live_pid), |pid| {
            marked_member_blocks(pid, MARKER)
        });
        assert!(matches!(marked, Ok(true)), "{marked:?}");
        let held_live = group_stopped_in(with_live.path(), &artifacts(live_pid), |pid| {
            marked_member_blocks(pid, MARKER)
        });
        assert!(
            matches!(held_live, Ok(false)),
            "a live marked member must still hold the group: {held_live:?}"
        );
    }
}
