//! Smoke test for the OpenAPI document generated by `calm_server::openapi`.
//!
//! Asserts every route we annotated is present in `paths`, every component
//! schema is present in `components.schemas`, and the JSON serialization
//! round-trips cleanly. The frontend toolchain consumes this exact JSON via
//! `GET /api/openapi.json`, so a missing schema here is a wire-types
//! contract violation.

use calm_server::openapi::ApiDoc;
use utoipa::OpenApi;

#[test]
fn document_contains_every_annotated_path() {
    let doc = ApiDoc::openapi();
    let expected_paths = [
        "/api/areas",
        "/api/areas/{id}",
        "/api/areas/{area_id}/tracks",
        "/api/tracks",
        "/api/tracks/{id}",
        "/api/tracks/{track_id}/cards",
        "/api/cards/{id}",
        "/api/cards/{id}/planner/input",
        // #1505 PR2. `openapi.rs`'s `paths(...)` is hand-maintained, and
        // omitting a handler there is silent: the drift gate compares the
        // generated files against themselves, so a route that never entered
        // the document never enters either generated client and nothing goes
        // red. This line is the guard.
        "/api/cards/{id}/planner/input/{entry_id}",
        // #1505 S4-3 — the model write port. Same guard, same reason.
        "/api/cards/{id}/planner/model",
        "/api/cards/{id}/planner/reset",
        "/api/cards/{card_id}/terminal",
        "/api/tracks/{track_id}/terminal-cards",
        "/api/tracks/{track_id}/codex-cards",
        "/api/overlays",
        "/api/overlays/delete",
        "/api/plugins",
        "/api/plugins/views",
        "/api/plugins/install",
        "/api/plugins/{id}",
        "/api/plugins/{id}/enable",
        "/api/plugins/{id}/disable",
        "/api/plugins/{id}/config",
        "/api/plugins/{id}/log",
        "/api/plugins/{id}/reload",
        "/api/plugins/{id}/rotate-token",
        "/api/plugins/{id}/resources/{view_id}",
        "/api/plugins/{id}/tool-call",
    ];
    for path in expected_paths {
        assert!(
            doc.paths.paths.contains_key(path),
            "expected path `{path}` in OpenAPI document; got: {:?}",
            doc.paths.paths.keys().collect::<Vec<_>>()
        );
    }
}

/// #1505 S4 review — a required-but-nullable body field is two independent
/// facts, and only one of them is enforced by the type.
///
/// `serde` makes `model` / `reasoning_effort` mandatory through a
/// `deserialize_with`; `utoipa` derives optionality from the `Option<T>` in
/// the field type and cannot see that attribute. They drifted apart in the
/// first cut: the published document said both were optional while the handler
/// answered 422 for omitting one, so a client generated from either
/// checked-in copy conformed to the contract and was broken by it. Neither
/// the OpenAPI drift gate nor the round-trip test above can notice — the
/// drift gate compares the generated files against themselves.
#[test]
fn a_body_field_that_refuses_omission_is_published_as_required() {
    let doc = ApiDoc::openapi();
    let components = doc.components.as_ref().expect("components present");
    let body = components
        .schemas
        .get("SetPlannerModelBody")
        .expect("SetPlannerModelBody is a component schema");
    let json = serde_json::to_value(body).expect("schema serializes");
    let required: Vec<&str> = json
        .get("required")
        .and_then(|value| value.as_array())
        .map(|items| items.iter().filter_map(|v| v.as_str()).collect())
        .unwrap_or_default();
    assert!(
        required.contains(&"model") && required.contains(&"reasoning_effort"),
        "both keys are refused when omitted, so the document must say so; got required={required:?} \
         in {json}"
    );
}

#[test]
fn document_does_not_advertise_retired_area_conversation_routes() {
    let doc = ApiDoc::openapi();
    for path in [
        "/api/areas/{area_id}/conversations",
        "/api/areas/{area_id}/chat-track/ensure",
    ] {
        assert!(
            !doc.paths.paths.contains_key(path),
            "retired path `{path}` is still advertised"
        );
    }
}

#[test]
fn document_contains_every_wire_model() {
    let doc = ApiDoc::openapi();
    let components = doc
        .components
        .as_ref()
        .expect("components present in OpenAPI document");
    let schemas: Vec<&String> = components.schemas.keys().collect();
    let expected_schemas = [
        // domain models
        "Area",
        "NewArea",
        "AreaPatch",
        "Track",
        "NewTrack",
        "CreateTrackRequest",
        "TrackPatch",
        "TrackDetail",
        "Card",
        "NewCard",
        "CardPatch",
        "SendPlannerInputRequest",
        "SendPlannerInputResponse",
        // #1505 PR2 — the queue write port.
        "EditPlannerInputBody",
        "DeletePlannerInputBody",
        "PlannerInputMutationResponse",
        "PlannerInputStaleBody",
        // #1505 S4-3 — the model write port.
        "SetPlannerModelBody",
        "SetPlannerModelResponse",
        "ResetPlannerCardResponse",
        "Overlay",
        "NewOverlay",
        "Terminal",
        "Plugin",
        // route-local DTOs
        "CreateAreaRequest",
        "CreateCardBody",
        "ViaToolCall",
        "NewTerminalCardBody",
        "NewCodexCardBody",
        "OverlayQuery",
        "OverlayDeleteBody",
        "InstallBody",
        "InstallSource",
        "PluginDetail",
        "PluginListItem",
        "ToolCallBody",
        "ViewCatalogEntry",
        "ViewSizeWire",
        // shared error response
        "ErrorBody",
    ];
    for name in expected_schemas {
        assert!(
            schemas.iter().any(|s| s.as_str() == name),
            "expected schema `{name}` in OpenAPI document; got: {:?}",
            schemas
        );
    }
}

#[test]
fn area_defaults_are_required_nullable_output_fields() {
    let json = serde_json::to_value(ApiDoc::openapi()).expect("OpenAPI doc serializes to JSON");
    let area = json
        .pointer("/components/schemas/Area")
        .expect("Area schema is present");
    let required = area
        .get("required")
        .and_then(|value| value.as_array())
        .expect("Area required list is present");

    for field in ["default_template_id", "default_cwd"] {
        assert!(
            required.iter().any(|value| value.as_str() == Some(field)),
            "Area.{field} is always serialized and must be required in OpenAPI: {area}"
        );
        let types = area
            .pointer(&format!("/properties/{field}/type"))
            .and_then(|value| value.as_array())
            .expect("nullable Area default has an OpenAPI type union");
        for expected in ["string", "null"] {
            assert!(
                types.iter().any(|value| value.as_str() == Some(expected)),
                "Area.{field} must allow {expected}: {area}"
            );
        }
    }
}

#[test]
fn document_serializes_to_json() {
    let doc = ApiDoc::openapi();
    let json = serde_json::to_value(&doc).expect("OpenAPI doc serializes to JSON");
    // Spec must declare itself as OpenAPI 3.x — `openapi` field with a
    // version string is the entry point clients sniff.
    assert!(
        json.get("openapi")
            .and_then(|v| v.as_str())
            .map(|s| s.starts_with("3."))
            .unwrap_or(false),
        "OpenAPI document missing/invalid `openapi` version field: {json}"
    );
    let paths = json
        .get("paths")
        .and_then(|v| v.as_object())
        .expect("paths present");
    assert!(!paths.is_empty(), "paths must not be empty");
    let schemas = json
        .pointer("/components/schemas")
        .and_then(|v| v.as_object())
        .expect("components.schemas present");
    assert!(!schemas.is_empty(), "schemas must not be empty");
}
