// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Placeholder for the Plate/Slate-compatible editor value. Replaced in
 * Spike Day 1 with the real AST node tree. Kept as `serde_json::Value`
 * for v0 so the wire format is open-ended while the schema stabilizes.
 */
export type EditorDoc = { value: unknown, };
