import { readFile, writeFile } from 'node:fs/promises';
import { isIP } from 'node:net';

const root = new URL('../', import.meta.url);
if (process.argv.length > 3) throw new Error('Usage: npm run configure -- [profile.json]');
const profile = JSON.parse(await readFile(process.argv[2] ?? new URL('server-profile.json', root), 'utf8'));
if (typeof profile.defaultServer !== 'string' || !Array.isArray(profile.httpOrigins) || typeof profile.allowConfiguredHttp !== 'boolean') {
  throw new Error('defaultServer, httpOrigins and allowConfiguredHttp are required');
}
for (const origin of profile.httpOrigins) {
  const url = new URL(origin);
  if (url.protocol !== 'http:' || origin !== url.origin || isIP(url.hostname) !== 4) {
    throw new Error('HTTP exceptions must be explicit IPv4 origins without credentials or paths');
  }
}
if (profile.defaultServer !== '') {
  const defaultUrl = new URL(profile.defaultServer);
  if (profile.defaultServer !== defaultUrl.origin ||
      (defaultUrl.protocol !== 'https:' && !profile.httpOrigins.includes(profile.defaultServer))) {
    throw new Error('defaultServer must be empty, an HTTPS origin, or an explicit HTTP exception');
  }
}
await writeFile(new URL('www/server-config.js', root),
  '// Generated by npm run configure from the selected server profile.\n' +
  `export const defaultServer = ${JSON.stringify(profile.defaultServer)};\n` +
  `export const httpOrigins = Object.freeze(${JSON.stringify(profile.httpOrigins, null, 2)});\n`);
const hosts = [...new Set(profile.httpOrigins.map((origin) => new URL(origin).hostname))];
const exceptions = hosts.length === 0 ? '' : `\n  <domain-config cleartextTrafficPermitted="true">\n${
  hosts.map((host) => `    <domain includeSubdomains="false">${host}</domain>`).join('\n')
}\n  </domain-config>`;
await writeFile(new URL('src-tauri/gen/android/app/src/main/res/xml/network_security_config.xml', root),
  '<?xml version="1.0" encoding="utf-8"?>\n' +
  '<!-- Generated by npm run configure from the selected server profile. -->\n' +
  `<network-security-config>\n  <base-config cleartextTrafficPermitted="${profile.allowConfiguredHttp ? 'true' : 'false'}"/>${exceptions}\n</network-security-config>\n`);
