import { useEffect, useMemo, useRef } from 'react';
import { sharedEventStream } from '../api/events';
import { useOverlaysByKindQuery } from '../api/queries';
import type { KernelOverlay } from '../api/wire';
import type { WireEvent } from '../api/wire';
import { isSpecHarnessPayload } from '../cards/builtins/spec';
import type { StatusOverlayPayload } from '../cards/overlayRegistry';
import { useReducer } from '../shared/state';
import type { WaveCardSlot } from '../types';

export interface EventLineEntry {
  /** Stable dedup key for React `key`. */
  id: string;
  /** Owning wave; used to synchronously hide stale entries on wave switches. */
  waveId: string;
  /** Stable semantic identity used for adjacent replay/live dedup. */
  identityKey: string;
  /** Unix millis when the event occurred. */
  time: number;
  /** Visual tone - drives node-dot color + tag color. */
  tone: 'default' | 'accent' | 'amber';
  /** Bold title. */
  title: string;
  /** Mono uppercase tag in the chip. */
  tag: string;
  /** One-sentence detail (may contain `<code>` segments). */
  description: string;
  /** Aggregation counter (incremented on repeated identical events). */
  count?: number;
}

export interface UseEventLineOptions {
  /** Cap on retained entries (default 40). */
  maxEntries?: number;
  /** Window in ms for adjacent-merge dedup (default 30_000). */
  dedupWindowMs?: number;
}

type EventLineTone = EventLineEntry['tone'];

interface EventLineScope {
  waveId: string;
  cardIdSet: ReadonlySet<string>;
  idempotencyKeySet: ReadonlySet<string>;
}

export type EventLineReducerAction =
  | { type: 'event'; ev: WireEvent; now?: number; scope?: EventLineScope }
  | { type: 'reset' };

interface EventLineState {
  entries: EventLineEntry[];
  waveId: string;
  cardIdSet: Set<string>;
  idempotencyKeySet: Set<string>;
}

type EventLineStateAction =
  | { type: 'event'; ev: WireEvent; now?: number }
  | { type: 'reset-entries' }
  | { type: 'reset-scope'; waveId: string }
  | {
      type: 'merge-scope';
      waveId: string;
      cardIds: ReadonlySet<string>;
      idempotencyKeys: ReadonlySet<string>;
    };

const DEFAULT_MAX_ENTRIES = 40;
const DEFAULT_DEDUP_WINDOW_MS = 30_000;

function resolveOptions(options?: UseEventLineOptions): Required<UseEventLineOptions> {
  const maxEntries =
    typeof options?.maxEntries === 'number' && Number.isFinite(options.maxEntries)
      ? Math.max(0, Math.floor(options.maxEntries))
      : DEFAULT_MAX_ENTRIES;
  const dedupWindowMs =
    typeof options?.dedupWindowMs === 'number' &&
    Number.isFinite(options.dedupWindowMs)
      ? Math.max(0, options.dedupWindowMs)
      : DEFAULT_DEDUP_WINDOW_MS;
  return { maxEntries, dedupWindowMs };
}

function code(value: string): string {
  return `<code>${value}</code>`;
}

function shortId(value: string): string {
  return value.length > 12 ? value.slice(0, 12) : value;
}

function makeEntry(
  ev: WireEvent,
  now: number,
  waveId: string,
  title: string,
  tag: string,
  tone: EventLineTone,
  description: string,
  identityKey: string,
): EventLineEntry {
  return {
    id: `${ev.ev}:${identityKey}:${now}`,
    waveId,
    identityKey,
    time: now,
    tone,
    title,
    tag,
    description,
  };
}

function isHookStop(kind: string): boolean {
  const normalized = kind.toLowerCase();
  return normalized === 'stop' || normalized.endsWith('.stop');
}

function isAgentRuntimeKind(kind: string): boolean {
  return kind === 'shared-spec' || kind === 'codex' || kind === 'claude';
}

export function eventToLineEntry(
  ev: WireEvent,
  now = Date.now(),
  waveId = eventWaveId(ev) ?? '',
): EventLineEntry | null {
  const entry = (
    title: string,
    tag: string,
    tone: EventLineTone,
    description: string,
    identityKey: string,
  ) => makeEntry(ev, now, waveId, title, tag, tone, description, identityKey);

  switch (ev.ev) {
    case 'wave.report_edited': {
      if (ev.data.author === 'user') {
        return entry(
          'Report edited',
          'user',
          'default',
          `User edited report card ${code(shortId(ev.data.card_id))}.`,
          `report-edit:${ev.data.author}:${ev.data.edit_id}`,
        );
      }

      const author =
        ev.data.author === 'kernel' ? 'the kernel' : 'the spec agent';
      return entry(
        'Report regenerated',
        'agent',
        'accent',
        `Report card ${code(shortId(ev.data.card_id))} was regenerated by ${author}.`,
        `report-edit:${ev.data.author}:${ev.data.edit_id}`,
      );
    }

    case 'card.added': {
      if (
        ev.data.kind === 'wave-report' ||
        ev.data.kind === 'spec' ||
        isSpecHarnessPayload(ev.data.payload)
      ) {
        return null;
      }
      return entry(
        `Worker added: ${ev.data.kind}`,
        'worker',
        'default',
        `Card ${code(shortId(ev.data.id))} joined the wave.`,
        `card:${ev.ev}:${ev.data.id}`,
      );
    }

    case 'card.deleted':
      return entry(
        'Card removed',
        'worker',
        'default',
        `Card ${code(shortId(ev.data.id))} was removed.`,
        `card:${ev.ev}:${ev.data.id}`,
      );

    case 'card.updated':
      return null;

    case 'wave.lifecycle_changed':
      return entry(
        `${ev.data.from} → ${ev.data.to}`,
        'lifecycle',
        'default',
        `Wave lifecycle moved from ${code(ev.data.from)} to ${code(ev.data.to)}.`,
        `lifecycle:${ev.data.from}->${ev.data.to}`,
      );

    case 'runtime.started':
      if (!isAgentRuntimeKind(ev.data.kind)) return null;
      return entry(
        'Agent started',
        'agent',
        'accent',
        `${ev.data.kind} runtime ${code(shortId(ev.data.runtime_id))} started.`,
        `runtime:${ev.ev}:${ev.data.runtime_id}`,
      );

    case 'runtime.status_changed':
      if (ev.data.new_status !== 'failed') return null;
      return entry(
        'Runtime failed',
        'alert',
        'amber',
        `Runtime ${code(shortId(ev.data.runtime_id))} changed from ${code(ev.data.old_status)} to ${code(ev.data.new_status)}.`,
        `runtime:${ev.ev}:${ev.data.runtime_id}:${ev.data.new_status}`,
      );

    case 'task.completed':
      return entry(
        'Task completed',
        'task',
        'default',
        `Worker task ${code(shortId(ev.data.idempotency_key))} completed.`,
        `task:${ev.ev}:${ev.data.idempotency_key}`,
      );

    case 'task.failed':
      return entry(
        'Task failed',
        'alert',
        'amber',
        `Worker task ${code(shortId(ev.data.idempotency_key))} failed.`,
        `task:${ev.ev}:${ev.data.idempotency_key}`,
      );

    case 'codex.hook':
    case 'claude.hook': {
      if (!isHookStop(ev.data.kind)) return null;
      const provider = ev.ev === 'codex.hook' ? 'Codex' : 'Claude';
      return entry(
        'Worker hook completed',
        'hook',
        'default',
        `${provider} hook ${code(shortId(ev.data.hook_idempotency_key))} completed.`,
        `hook:${ev.ev}:${ev.data.card_id}:${ev.data.hook_idempotency_key}`,
      );
    }

    default:
      return null;
  }
}

export function eventLineDedupeKey(entry: EventLineEntry): string {
  return entry.identityKey;
}

export function filterEventLineEntriesForWave(
  entries: EventLineEntry[],
  waveId: string,
): EventLineEntry[] {
  return entries.filter((entry) => entry.waveId === waveId);
}

export function reduceEventLineEntries(
  entries: EventLineEntry[],
  action: EventLineReducerAction,
  options?: UseEventLineOptions,
): EventLineEntry[] {
  if (action.type === 'reset') return [];

  if (
    action.scope &&
    !eventBelongsToWave(action.ev, action.scope.waveId, action.scope)
  ) {
    return entries;
  }

  const entry = eventToLineEntry(
    action.ev,
    action.now,
    action.scope?.waveId,
  );
  if (!entry) return entries;

  const { maxEntries, dedupWindowMs } = resolveOptions(options);
  if (maxEntries === 0) return [];

  const newest = entries[0];
  if (
    newest &&
    eventLineDedupeKey(newest) === eventLineDedupeKey(entry) &&
    Math.abs(entry.time - newest.time) <= dedupWindowMs
  ) {
    return [
      {
        ...newest,
        time: entry.time,
        description: entry.description,
        count: (newest.count ?? 1) + 1,
      },
      ...entries.slice(1),
    ];
  }

  return [entry, ...entries].slice(0, maxEntries);
}

function eventWaveId(ev: WireEvent): string | undefined {
  switch (ev.ev) {
    case 'wave.updated':
    case 'wave.deleted':
    case 'wave.lifecycle_changed':
      return ev.data.id;
    case 'card.added':
    case 'card.updated':
    case 'card.deleted':
    case 'harness.item.added':
    case 'harness.phase.changed':
    case 'harness.transcript.cleared':
    case 'harness.user_message.enqueued':
    case 'wave.report_edited':
      return ev.data.wave_id;
    default:
      return undefined;
  }
}

function eventCardId(ev: WireEvent): string | undefined {
  switch (ev.ev) {
    case 'runtime.started':
    case 'runtime.status_changed':
    case 'runtime.superseded':
    case 'codex.hook':
    case 'claude.hook':
    case 'terminal.deleted':
      return ev.data.card_id;
    default:
      return undefined;
  }
}

function eventTaskIdempotencyKey(ev: WireEvent): string | undefined {
  switch (ev.ev) {
    case 'task.completed':
    case 'task.failed':
      return ev.data.idempotency_key;
    default:
      return undefined;
  }
}

function eventBelongsToWave(
  ev: WireEvent,
  waveId: string,
  scope: EventLineScope,
): boolean {
  switch (ev.ev) {
    case 'wave.updated':
    case 'wave.deleted':
    case 'wave.lifecycle_changed':
      return ev.data.id === waveId;
    case 'card.added':
    case 'card.updated':
    case 'card.deleted':
      return ev.data.wave_id === waveId;
    case 'harness.item.added':
    case 'harness.phase.changed':
    case 'harness.transcript.cleared':
    case 'harness.user_message.enqueued':
    case 'wave.report_edited':
      return ev.data.wave_id === waveId;
    case 'runtime.started':
    case 'runtime.status_changed':
    case 'runtime.superseded':
    case 'codex.hook':
    case 'claude.hook': {
      const cardId = eventCardId(ev);
      return typeof cardId === 'string' && scope.cardIdSet.has(cardId);
    }
    case 'task.completed':
    case 'task.failed': {
      const idempotencyKey = eventTaskIdempotencyKey(ev);
      return (
        typeof idempotencyKey === 'string' &&
        scope.idempotencyKeySet.has(idempotencyKey)
      );
    }
    default:
      return false;
  }
}

function readIdempotencyKey(value: unknown): string | undefined {
  if (!value || typeof value !== 'object') return undefined;
  const candidate = (value as { idempotency_key?: unknown; idempotencyKey?: unknown })
    .idempotency_key ?? (value as { idempotencyKey?: unknown }).idempotencyKey;
  return typeof candidate === 'string' && candidate.length > 0
    ? candidate
    : undefined;
}

function cardTaskIdempotencyKey(slot: WaveCardSlot): string | undefined {
  if (slot.kind !== 'card') return undefined;
  return readIdempotencyKey(slot.card);
}

function eventCardIdempotencyKey(ev: WireEvent): string | undefined {
  switch (ev.ev) {
    case 'card.added':
    case 'card.updated':
      return readIdempotencyKey(ev.data.payload);
    default:
      return undefined;
  }
}

function deriveScopeFromCards(cards: WaveCardSlot[]): {
  cardIdSet: Set<string>;
  idempotencyKeySet: Set<string>;
} {
  const cardIdSet = new Set<string>();
  const idempotencyKeySet = new Set<string>();

  for (const slot of cards) {
    if (slot.kind === 'card' && slot.card.id) {
      cardIdSet.add(slot.card.id);
    }
    const idempotencyKey = cardTaskIdempotencyKey(slot);
    if (idempotencyKey) {
      idempotencyKeySet.add(idempotencyKey);
    }
  }

  return { cardIdSet, idempotencyKeySet };
}

export function createEventLineState(
  waveId: string,
  cards: WaveCardSlot[],
): EventLineState {
  return { entries: [], waveId, ...deriveScopeFromCards(cards) };
}

function updateScopeFromEvent(
  state: EventLineState,
  ev: WireEvent,
): EventLineState {
  switch (ev.ev) {
    case 'card.added': {
      if (ev.data.wave_id !== state.waveId) return state;
      const cardIdSet = new Set(state.cardIdSet);
      cardIdSet.add(ev.data.id);
      const idempotencyKey = eventCardIdempotencyKey(ev);
      if (!idempotencyKey) {
        return { ...state, cardIdSet };
      }
      const idempotencyKeySet = new Set(state.idempotencyKeySet);
      idempotencyKeySet.add(idempotencyKey);
      return { ...state, cardIdSet, idempotencyKeySet };
    }

    case 'card.updated': {
      if (ev.data.wave_id !== state.waveId) return state;
      const idempotencyKey = eventCardIdempotencyKey(ev);
      if (!idempotencyKey || state.idempotencyKeySet.has(idempotencyKey)) {
        return state;
      }
      const idempotencyKeySet = new Set(state.idempotencyKeySet);
      idempotencyKeySet.add(idempotencyKey);
      return { ...state, idempotencyKeySet };
    }

    case 'card.deleted': {
      if (ev.data.wave_id !== state.waveId || !state.cardIdSet.has(ev.data.id)) {
        return state;
      }
      const cardIdSet = new Set(state.cardIdSet);
      cardIdSet.delete(ev.data.id);
      return { ...state, cardIdSet };
    }

    default:
      return state;
  }
}

export function reduceEventLineState(
  state: EventLineState,
  action: EventLineStateAction,
  options?: UseEventLineOptions,
): EventLineState {
  switch (action.type) {
    case 'reset-entries':
      return { ...state, entries: [] };

    case 'reset-scope':
      return {
        entries: [],
        waveId: action.waveId,
        cardIdSet: new Set<string>(),
        idempotencyKeySet: new Set<string>(),
      };

    case 'merge-scope': {
      if (action.waveId !== state.waveId) return state;
      return {
        ...state,
        cardIdSet: new Set([...state.cardIdSet, ...action.cardIds]),
        idempotencyKeySet: new Set([
          ...state.idempotencyKeySet,
          ...action.idempotencyKeys,
        ]),
      };
    }

    case 'event': {
      if (!eventBelongsToWave(action.ev, state.waveId, state)) return state;
      const scopedState = updateScopeFromEvent(state, action.ev);
      const entries = reduceEventLineEntries(
        scopedState.entries,
        { type: 'event', ev: action.ev, now: action.now, scope: scopedState },
        options,
      );
      return entries === scopedState.entries
        ? scopedState
        : { ...scopedState, entries };
    }
  }
}

export function useEventLineEntries(
  waveId: string,
  cards: WaveCardSlot[],
  options?: UseEventLineOptions,
): EventLineEntry[] {
  const maxEntries = options?.maxEntries;
  const dedupWindowMs = options?.dedupWindowMs;
  const resolvedOptions = useMemo(
    () => resolveOptions({ maxEntries, dedupWindowMs }),
    [dedupWindowMs, maxEntries],
  );
  const propScope = useMemo(() => deriveScopeFromCards(cards), [cards]);
  const waveIdRef = useRef(waveId);
  waveIdRef.current = waveId;
  const [state, dispatch] = useReducer(
    (state: EventLineState, action: EventLineStateAction) =>
      reduceEventLineState(state, action, resolvedOptions),
    { waveId, cards },
    ({ waveId, cards }) => createEventLineState(waveId, cards),
  );

  useEffect(() => {
    dispatch({ type: 'reset-entries' });
  }, [resolvedOptions.maxEntries, resolvedOptions.dedupWindowMs]);

  useEffect(() => {
    dispatch({ type: 'reset-scope', waveId });
  }, [waveId]);

  useEffect(() => {
    dispatch({
      type: 'merge-scope',
      waveId: waveIdRef.current,
      cardIds: propScope.cardIdSet,
      idempotencyKeys: propScope.idempotencyKeySet,
    });
  }, [propScope]);

  useEffect(() => {
    if (!waveId) return;

    const stream = sharedEventStream();
    const off = stream.on((ev) => {
      dispatch({ type: 'event', ev });
    });

    return () => {
      off();
    };
  }, [waveId]);

  return useMemo(
    () => filterEventLineEntriesForWave(state.entries, waveId),
    [state.entries, waveId],
  );
}

function isRuntimeBearingCardType(type: string): boolean {
  // Overlay-backed LIVE covers only hook agents; WaveCardSlot carries no terminal runtime state.
  return (
    type === 'spec' ||
    type === 'codex' ||
    type === 'claude'
  );
}

function selectRuntimeCardIds(cards: WaveCardSlot[]): Set<string> {
  const cardIds = new Set<string>();
  for (const slot of cards) {
    if (
      slot.kind === 'card' &&
      slot.card.id &&
      isRuntimeBearingCardType(slot.card.type)
    ) {
      cardIds.add(slot.card.id);
    }
  }
  return cardIds;
}

function isStatusOverlayPayload(payload: unknown): payload is StatusOverlayPayload {
  return (
    payload !== null &&
    typeof payload === 'object' &&
    typeof (payload as { state?: unknown }).state === 'string'
  );
}

export function isRuntimeLiveState(state: string | undefined): boolean {
  if (typeof state !== 'string') return false;
  return ['running', 'issuing', 'starting', 'working', 'turnrunning'].includes(
    state.toLowerCase(),
  );
}

export function selectAnyRuntimeLive(
  cards: WaveCardSlot[],
  overlays: readonly KernelOverlay[],
): boolean {
  const runtimeCardIds = selectRuntimeCardIds(cards);
  if (runtimeCardIds.size === 0) return false;

  return overlays.some(
    (overlay) =>
      overlay.entity_kind === 'card' &&
      overlay.kind === 'status' &&
      runtimeCardIds.has(overlay.entity_id) &&
      isStatusOverlayPayload(overlay.payload) &&
      isRuntimeLiveState(overlay.payload.state),
  );
}

export function useAnyRuntimeLive(
  waveId: string,
  cards: WaveCardSlot[],
): boolean {
  const runtimeCardIds = useMemo(() => selectRuntimeCardIds(cards), [cards]);
  const overlaysQuery = useOverlaysByKindQuery('card', {
    enabled: waveId.length > 0 && runtimeCardIds.size > 0,
  });
  return useMemo(
    () => selectAnyRuntimeLive(cards, overlaysQuery.data ?? []),
    [cards, overlaysQuery.data],
  );
}
