import { useEffect, useMemo } from 'react';
import { sharedEventStream } from '../api/events';
import type { WireEvent } from '../api/wire';
import { useCardStatusOverlay } from '../cards/overlayRegistry';
import { useReducer } from '../shared/state';
import type { WaveCardSlot } from '../types';

export interface EventLineEntry {
  /** Stable dedup key for React `key`. */
  id: string;
  /** Owning wave; used to synchronously hide stale entries on wave switches. */
  waveId: string;
  /** Stable semantic identity used for adjacent replay/live dedup. */
  identityKey: string;
  /** Unix millis when the event occurred. */
  time: number;
  /** Visual tone - drives node-dot color + tag color. */
  tone: 'default' | 'accent' | 'amber';
  /** Bold title. */
  title: string;
  /** Mono uppercase tag in the chip. */
  tag: string;
  /** One-sentence detail (may contain `<code>` segments). */
  description: string;
  /** Aggregation counter (incremented on repeated identical events). */
  count?: number;
}

export interface UseEventLineOptions {
  /** Cap on retained entries (default 40). */
  maxEntries?: number;
  /** Window in ms for adjacent-merge dedup (default 30_000). */
  dedupWindowMs?: number;
}

type EventLineTone = EventLineEntry['tone'];

interface EventLineScope {
  waveId: string;
  cardIdSet: ReadonlySet<string>;
  taskIdempotencyKeySet: ReadonlySet<string>;
}

export type EventLineReducerAction =
  | { type: 'event'; ev: WireEvent; now?: number; scope?: EventLineScope }
  | { type: 'reset' };

const DEFAULT_MAX_ENTRIES = 40;
const DEFAULT_DEDUP_WINDOW_MS = 30_000;

function resolveOptions(options?: UseEventLineOptions): Required<UseEventLineOptions> {
  const maxEntries =
    typeof options?.maxEntries === 'number' && Number.isFinite(options.maxEntries)
      ? Math.max(0, Math.floor(options.maxEntries))
      : DEFAULT_MAX_ENTRIES;
  const dedupWindowMs =
    typeof options?.dedupWindowMs === 'number' &&
    Number.isFinite(options.dedupWindowMs)
      ? Math.max(0, options.dedupWindowMs)
      : DEFAULT_DEDUP_WINDOW_MS;
  return { maxEntries, dedupWindowMs };
}

function code(value: string): string {
  return `<code>${value}</code>`;
}

function shortId(value: string): string {
  return value.length > 12 ? value.slice(0, 12) : value;
}

function makeEntry(
  ev: WireEvent,
  now: number,
  waveId: string,
  title: string,
  tag: string,
  tone: EventLineTone,
  description: string,
  identityKey: string,
): EventLineEntry {
  return {
    id: `${ev.ev}:${identityKey}:${now}`,
    waveId,
    identityKey,
    time: now,
    tone,
    title,
    tag,
    description,
  };
}

function isHookStop(kind: string): boolean {
  const normalized = kind.toLowerCase();
  return normalized === 'stop' || normalized.endsWith('.stop');
}

function isAgentRuntimeKind(kind: string): boolean {
  return kind === 'shared-spec' || kind === 'codex' || kind === 'claude';
}

export function eventToLineEntry(
  ev: WireEvent,
  now = Date.now(),
  waveId = eventWaveId(ev) ?? '',
): EventLineEntry | null {
  const entry = (
    title: string,
    tag: string,
    tone: EventLineTone,
    description: string,
    identityKey: string,
  ) => makeEntry(ev, now, waveId, title, tag, tone, description, identityKey);

  switch (ev.ev) {
    case 'wave.report_edited': {
      if (ev.data.author === 'user') {
        return entry(
          'Report edited',
          'user',
          'default',
          `User edited report card ${code(shortId(ev.data.card_id))}.`,
          `report-edit:${ev.data.author}:${ev.data.edit_id}`,
        );
      }

      const author =
        ev.data.author === 'kernel' ? 'the kernel' : 'the spec agent';
      return entry(
        'Report regenerated',
        'agent',
        'accent',
        `Report card ${code(shortId(ev.data.card_id))} was regenerated by ${author}.`,
        `report-edit:${ev.data.author}:${ev.data.edit_id}`,
      );
    }

    case 'card.added': {
      if (ev.data.kind === 'wave-report' || ev.data.kind === 'spec') return null;
      return entry(
        `Worker added: ${ev.data.kind}`,
        'worker',
        'default',
        `Card ${code(shortId(ev.data.id))} joined the wave.`,
        `card:${ev.ev}:${ev.data.id}`,
      );
    }

    case 'card.deleted':
      return entry(
        'Card removed',
        'worker',
        'default',
        `Card ${code(shortId(ev.data.id))} was removed.`,
        `card:${ev.ev}:${ev.data.id}`,
      );

    case 'card.updated':
      return null;

    case 'wave.lifecycle_changed':
      return entry(
        `${ev.data.from} → ${ev.data.to}`,
        'lifecycle',
        'default',
        `Wave lifecycle moved from ${code(ev.data.from)} to ${code(ev.data.to)}.`,
        `lifecycle:${ev.data.from}->${ev.data.to}`,
      );

    case 'runtime.started':
      if (!isAgentRuntimeKind(ev.data.kind)) return null;
      return entry(
        'Agent started',
        'agent',
        'accent',
        `${ev.data.kind} runtime ${code(shortId(ev.data.runtime_id))} started.`,
        `runtime:${ev.ev}:${ev.data.runtime_id}`,
      );

    case 'runtime.status_changed':
      if (ev.data.new_status !== 'failed') return null;
      return entry(
        'Runtime failed',
        'alert',
        'amber',
        `Runtime ${code(shortId(ev.data.runtime_id))} changed from ${code(ev.data.old_status)} to ${code(ev.data.new_status)}.`,
        `runtime:${ev.ev}:${ev.data.runtime_id}:${ev.data.new_status}`,
      );

    case 'task.completed':
      return entry(
        'Task completed',
        'task',
        'default',
        `Worker task ${code(shortId(ev.data.idempotency_key))} completed.`,
        `task:${ev.ev}:${ev.data.idempotency_key}`,
      );

    case 'task.failed':
      return entry(
        'Task failed',
        'alert',
        'amber',
        `Worker task ${code(shortId(ev.data.idempotency_key))} failed.`,
        `task:${ev.ev}:${ev.data.idempotency_key}`,
      );

    case 'codex.hook':
    case 'claude.hook': {
      if (!isHookStop(ev.data.kind)) return null;
      const provider = ev.ev === 'codex.hook' ? 'Codex' : 'Claude';
      return entry(
        'Worker hook completed',
        'hook',
        'default',
        `${provider} hook ${code(shortId(ev.data.hook_idempotency_key))} completed.`,
        `hook:${ev.ev}:${ev.data.card_id}:${ev.data.hook_idempotency_key}`,
      );
    }

    default:
      return null;
  }
}

export function eventLineDedupeKey(entry: EventLineEntry): string {
  return entry.identityKey;
}

export function filterEventLineEntriesForWave(
  entries: EventLineEntry[],
  waveId: string,
): EventLineEntry[] {
  return entries.filter((entry) => entry.waveId === waveId);
}

export function reduceEventLineEntries(
  entries: EventLineEntry[],
  action: EventLineReducerAction,
  options?: UseEventLineOptions,
): EventLineEntry[] {
  if (action.type === 'reset') return [];

  if (
    action.scope &&
    !eventBelongsToWave(action.ev, action.scope.waveId, action.scope)
  ) {
    return entries;
  }

  const entry = eventToLineEntry(
    action.ev,
    action.now,
    action.scope?.waveId,
  );
  if (!entry) return entries;

  const { maxEntries, dedupWindowMs } = resolveOptions(options);
  if (maxEntries === 0) return [];

  const newest = entries[0];
  if (
    newest &&
    eventLineDedupeKey(newest) === eventLineDedupeKey(entry) &&
    Math.abs(entry.time - newest.time) <= dedupWindowMs
  ) {
    return [
      {
        ...newest,
        time: entry.time,
        description: entry.description,
        count: (newest.count ?? 1) + 1,
      },
      ...entries.slice(1),
    ];
  }

  return [entry, ...entries].slice(0, maxEntries);
}

function eventWaveId(ev: WireEvent): string | undefined {
  switch (ev.ev) {
    case 'wave.updated':
    case 'wave.deleted':
    case 'wave.lifecycle_changed':
      return ev.data.id;
    case 'card.added':
    case 'card.updated':
    case 'card.deleted':
    case 'harness.item.added':
    case 'harness.phase.changed':
    case 'harness.transcript.cleared':
    case 'harness.user_message.enqueued':
    case 'wave.report_edited':
      return ev.data.wave_id;
    default:
      return undefined;
  }
}

function eventCardId(ev: WireEvent): string | undefined {
  switch (ev.ev) {
    case 'runtime.started':
    case 'runtime.status_changed':
    case 'runtime.superseded':
    case 'codex.hook':
    case 'claude.hook':
    case 'terminal.deleted':
      return ev.data.card_id;
    default:
      return undefined;
  }
}

function eventTaskIdempotencyKey(ev: WireEvent): string | undefined {
  switch (ev.ev) {
    case 'task.completed':
    case 'task.failed':
      return ev.data.idempotency_key;
    default:
      return undefined;
  }
}

function eventBelongsToWave(
  ev: WireEvent,
  waveId: string,
  scope: EventLineScope,
): boolean {
  switch (ev.ev) {
    case 'wave.updated':
    case 'wave.deleted':
    case 'wave.lifecycle_changed':
      return ev.data.id === waveId;
    case 'card.added':
    case 'card.updated':
    case 'card.deleted':
      return ev.data.wave_id === waveId;
    case 'harness.item.added':
    case 'harness.phase.changed':
    case 'harness.transcript.cleared':
    case 'harness.user_message.enqueued':
    case 'wave.report_edited':
      return ev.data.wave_id === waveId;
    case 'runtime.started':
    case 'runtime.status_changed':
    case 'runtime.superseded':
    case 'codex.hook':
    case 'claude.hook': {
      const cardId = eventCardId(ev);
      return typeof cardId === 'string' && scope.cardIdSet.has(cardId);
    }
    case 'task.completed':
    case 'task.failed': {
      const idempotencyKey = eventTaskIdempotencyKey(ev);
      return (
        typeof idempotencyKey === 'string' &&
        scope.taskIdempotencyKeySet.has(idempotencyKey)
      );
    }
    default:
      return false;
  }
}

function cardTaskIdempotencyKey(slot: WaveCardSlot): string | undefined {
  if (slot.kind !== 'card') return undefined;
  const candidate = (slot.card as { idempotencyKey?: unknown }).idempotencyKey;
  return typeof candidate === 'string' && candidate.length > 0
    ? candidate
    : undefined;
}

function buildEventLineScope(
  waveId: string,
  cards: WaveCardSlot[],
): EventLineScope {
  const cardIdSet = new Set<string>();
  const taskIdempotencyKeySet = new Set<string>();

  for (const slot of cards) {
    if (slot.kind === 'card' && slot.card.id) {
      cardIdSet.add(slot.card.id);
    }
    const idempotencyKey = cardTaskIdempotencyKey(slot);
    if (idempotencyKey) {
      taskIdempotencyKeySet.add(idempotencyKey);
    }
  }

  return { waveId, cardIdSet, taskIdempotencyKeySet };
}

export function useEventLineEntries(
  waveId: string,
  cards: WaveCardSlot[],
  options?: UseEventLineOptions,
): EventLineEntry[] {
  const maxEntries = options?.maxEntries;
  const dedupWindowMs = options?.dedupWindowMs;
  const resolvedOptions = useMemo(
    () => resolveOptions({ maxEntries, dedupWindowMs }),
    [dedupWindowMs, maxEntries],
  );
  const eventLineScope = useMemo(
    () => buildEventLineScope(waveId, cards),
    [cards, waveId],
  );
  const [entries, dispatch] = useReducer(
    (state: EventLineEntry[], action: EventLineReducerAction) =>
      reduceEventLineEntries(state, action, resolvedOptions),
    [],
  );

  useEffect(() => {
    dispatch({ type: 'reset' });
  }, [waveId, resolvedOptions.maxEntries, resolvedOptions.dedupWindowMs]);

  useEffect(() => {
    if (!waveId) return;

    const stream = sharedEventStream();
    stream.addTopic(`wave:${waveId}`);
    const off = stream.on((ev) => {
      if (eventBelongsToWave(ev, waveId, eventLineScope)) {
        dispatch({ type: 'event', ev, scope: eventLineScope });
      }
    });

    return () => {
      off();
    };
  }, [eventLineScope, waveId]);

  return useMemo(
    () => filterEventLineEntriesForWave(entries, waveId),
    [entries, waveId],
  );
}

function selectSpecCardId(cards: WaveCardSlot[]): string | undefined {
  const slot = cards.find(
    (candidate) =>
      candidate.kind === 'card' && candidate.card.type === 'spec',
  );
  return slot?.kind === 'card' ? slot.card.id : undefined;
}

export function isRuntimeLiveState(state: string | undefined): boolean {
  if (typeof state !== 'string') return false;
  return ['running', 'issuing', 'working', 'turnrunning'].includes(
    state.toLowerCase(),
  );
}

export function useAnyRuntimeLive(
  _waveId: string,
  cards: WaveCardSlot[],
): boolean {
  const specCardId = useMemo(() => selectSpecCardId(cards), [cards]);
  const status = useCardStatusOverlay(specCardId);
  return isRuntimeLiveState(status?.state);
}
