-- Calm-server schema v1.
--
-- Conventions
--   * `id`           : TEXT (uuid-v4 hex, generated by server, never by client)
--   * `*_at`         : INTEGER unix millis (server-local clock)
--   * `sort`         : REAL — fractional-index order key (insert between by midpoint)
--   * JSON columns   : TEXT containing valid JSON; the kernel does not inspect contents
--                      of plugin-owned blobs (Card.payload, Overlay.payload).

CREATE TABLE coves (
    id          TEXT    PRIMARY KEY,
    name        TEXT    NOT NULL,
    color       TEXT    NOT NULL,
    sort        REAL    NOT NULL,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
);
CREATE INDEX idx_coves_sort ON coves(sort);

CREATE TABLE waves (
    id          TEXT    PRIMARY KEY,
    cove_id     TEXT    NOT NULL REFERENCES coves(id) ON DELETE CASCADE,
    title       TEXT    NOT NULL,
    sort        REAL    NOT NULL,
    archived_at INTEGER,
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
);
CREATE INDEX idx_waves_cove ON waves(cove_id, sort);

CREATE TABLE cards (
    id          TEXT    PRIMARY KEY,
    wave_id     TEXT    NOT NULL REFERENCES waves(id) ON DELETE CASCADE,
    kind        TEXT    NOT NULL,                 -- "terminal" | "plugin:<id>:<view>"
    sort        REAL    NOT NULL,
    payload     TEXT    NOT NULL DEFAULT '{}',    -- opaque JSON
    created_at  INTEGER NOT NULL,
    updated_at  INTEGER NOT NULL
);
CREATE INDEX idx_cards_wave ON cards(wave_id, sort);

CREATE TABLE overlays (
    id           TEXT    PRIMARY KEY,
    plugin_id    TEXT    NOT NULL,
    entity_kind  TEXT    NOT NULL,                -- "wave" | "card"
    entity_id    TEXT    NOT NULL,
    kind         TEXT    NOT NULL,                -- plugin-defined, e.g. "status"
    payload      TEXT    NOT NULL,                -- opaque JSON
    updated_at   INTEGER NOT NULL,
    UNIQUE (plugin_id, entity_kind, entity_id, kind)
);
CREATE INDEX idx_overlays_entity ON overlays(entity_kind, entity_id);

CREATE TABLE terminals (
    id            TEXT    PRIMARY KEY,
    card_id       TEXT    NOT NULL UNIQUE REFERENCES cards(id) ON DELETE CASCADE,
    program       TEXT    NOT NULL,
    cwd           TEXT    NOT NULL,
    env           TEXT    NOT NULL DEFAULT '{}',  -- JSON object
    daemon_handle TEXT,                            -- opaque, set by track D after spawn
    created_at    INTEGER NOT NULL
);

CREATE TABLE plugins (
    id            TEXT    PRIMARY KEY,
    version       TEXT    NOT NULL,
    install_path  TEXT    NOT NULL,
    manifest      TEXT    NOT NULL,               -- JSON-encoded manifest contents
    enabled       INTEGER NOT NULL DEFAULT 1,
    user_config   TEXT    NOT NULL DEFAULT '{}',
    installed_at  INTEGER NOT NULL,
    updated_at    INTEGER NOT NULL
);
