//! #1620 — hook signals for Planner-opened terminals.
//!
//! `calm.terminal.open` asks the terminal-create operation for
//! `planner_hooks`; the adapter then derives, from the card id it allocates,
//! a hooks-only Claude settings file under the server-owned
//! `<data_dir>/terminal-hooks/` directory and the env the existing
//! `neige-codex-bridge` contract needs (`NEIGE_CLAUDE_SETTINGS`,
//! `NEIGE_CARD_ID`, `NEIGE_CALM_BASE_URL`, `NEIGE_HOOK_PROVIDER`,
//! `NEIGE_HOOK_URL`). The Planner starts Claude with
//! `claude --settings "$NEIGE_CLAUDE_SETTINGS"`; nothing is installed into the
//! user's `~/.claude` or the project directory.
//!
//! Hook payloads reaching `/internal/claude/hook` for a Terminal card are
//! parsed into a bounded [`IncomingSignal`] and appended to the renderer
//! entry's ring. They are application data: forgeable by any local process,
//! never authority and never an instruction.
use crate::card_fsm::{CLAUDE_WORKER_HOOKS, ClaudeWorkerHook};
use crate::routes::claude_cards::{build_claude_settings_json_for, claude_hook_command};
use crate::routes::codex::to_snake_case;
use crate::terminal_renderer::{IncomingSignal, SIGNAL_MESSAGE_MAX_CHARS};
use serde_json::{Map, Value};
use std::path::{Path, PathBuf};

/// Claude Code hook events registered for a Planner terminal (exactly these).
pub const TERMINAL_HOOK_EVENTS: [&str; 7] = [
    "SessionStart",
    "UserPromptSubmit",
    "Stop",
    "Notification",
    "PermissionRequest",
    "SessionEnd",
    "SubagentStop",
];

/// snake_case names of [`TERMINAL_HOOK_EVENTS`], the vocabulary of
/// `signal_events` and of `wait.signal.event`.
pub const TERMINAL_SIGNAL_EVENTS: [&str; 7] = [
    "session_start",
    "user_prompt_submit",
    "stop",
    "notification",
    "permission_request",
    "session_end",
    "subagent_stop",
];

/// Default `signal_events` for `wait_for=signal`: the events after which the
/// Planner has something to read or decide.
pub const DEFAULT_SIGNAL_EVENTS: [&str; 4] =
    ["stop", "notification", "permission_request", "session_end"];

/// Env keys generated by the adapter for a `planner_hooks` terminal.
pub const TERMINAL_HOOK_ENV_KEYS: [&str; 5] = [
    "NEIGE_CLAUDE_SETTINGS",
    "NEIGE_CARD_ID",
    "NEIGE_CALM_BASE_URL",
    "NEIGE_HOOK_PROVIDER",
    "NEIGE_HOOK_URL",
];

/// Where generated settings live and how the bridge reaches the server.
#[derive(Clone, Debug)]
pub struct TerminalHookSettings {
    pub bridge_bin: PathBuf,
    pub base_url: String,
    /// Server-owned directory; every file in it is `<card_id>.json`.
    pub settings_dir: PathBuf,
}

impl TerminalHookSettings {
    pub fn settings_path(&self, card_id: &str) -> PathBuf {
        settings_path_in(&self.settings_dir, card_id)
    }

    pub fn hook_url(&self, card_id: &str) -> String {
        format!(
            "{}/internal/claude/hook?card_id={}",
            self.base_url.trim_end_matches('/'),
            card_id
        )
    }

    pub fn hook_command(&self, card_id: &str) -> String {
        claude_hook_command(&self.bridge_bin.to_string_lossy(), card_id, &self.base_url)
    }

    /// The generated env for `card_id`, keyed exactly by
    /// [`TERMINAL_HOOK_ENV_KEYS`].
    pub fn env(&self, card_id: &str) -> Map<String, Value> {
        let mut env = Map::new();
        env.insert(
            "NEIGE_CLAUDE_SETTINGS".into(),
            Value::String(self.settings_path(card_id).to_string_lossy().into_owned()),
        );
        env.insert("NEIGE_CARD_ID".into(), Value::String(card_id.to_owned()));
        env.insert(
            "NEIGE_CALM_BASE_URL".into(),
            Value::String(self.base_url.clone()),
        );
        env.insert("NEIGE_HOOK_PROVIDER".into(), Value::String("claude".into()));
        env.insert(
            "NEIGE_HOOK_URL".into(),
            Value::String(self.hook_url(card_id)),
        );
        env
    }

    /// Merge the generated env over the request env (generated keys win).
    pub fn merge_env(&self, request_env: &Value, card_id: &str) -> Value {
        let mut merged = request_env.as_object().cloned().unwrap_or_default();
        for (key, value) in self.env(card_id) {
            merged.insert(key, value);
        }
        Value::Object(merged)
    }

    pub fn settings_json(&self, card_id: &str) -> String {
        build_claude_settings_json_for(&self.hook_command(card_id), terminal_hooks())
    }

    /// mkdir + write the settings file; called before the child spawns.
    pub fn write_settings(&self, card_id: &str) -> crate::error::Result<PathBuf> {
        std::fs::create_dir_all(&self.settings_dir).map_err(|e| {
            crate::error::CalmError::Internal(format!(
                "mkdir terminal hook settings dir {}: {e}",
                self.settings_dir.display()
            ))
        })?;
        let path = self.settings_path(card_id);
        std::fs::write(&path, self.settings_json(card_id)).map_err(|e| {
            crate::error::CalmError::Internal(format!(
                "write terminal hook settings {}: {e}",
                path.display()
            ))
        })?;
        Ok(path)
    }
}

fn settings_path_in(dir: &Path, card_id: &str) -> PathBuf {
    dir.join(format!("{card_id}.json"))
}

/// Delete `<dir>/<card_id>.json` (best effort; a missing file is fine). The
/// path is derived from the server-owned directory, never from env.
pub fn remove_settings_file(dir: &Path, card_id: &str) {
    if card_id.is_empty() || card_id.contains('/') || card_id.contains("..") {
        return;
    }
    let path = settings_path_in(dir, card_id);
    match std::fs::remove_file(&path) {
        Ok(()) => {
            tracing::debug!(target: "terminal.hooks", path = %path.display(), "removed terminal hook settings")
        }
        Err(e) if e.kind() == std::io::ErrorKind::NotFound => {}
        Err(e) => {
            tracing::warn!(target: "terminal.hooks", path = %path.display(), error = %e, "removing terminal hook settings failed")
        }
    }
}

/// The `CLAUDE_WORKER_HOOKS` rows for [`TERMINAL_HOOK_EVENTS`], in table
/// order, so matcher flags stay faithful to the worker settings.
pub(crate) fn terminal_hooks() -> Vec<ClaudeWorkerHook> {
    CLAUDE_WORKER_HOOKS
        .iter()
        .filter(|hook| TERMINAL_HOOK_EVENTS.contains(&hook.event_name))
        .copied()
        .collect()
}

/// Parse a hook body into a bounded signal. `Err` names why the payload is
/// malformed or unknown; the caller logs and still acknowledges the hook.
pub fn parse_terminal_signal(payload: &Value) -> Result<IncomingSignal, String> {
    let object = payload
        .as_object()
        .ok_or_else(|| "hook payload is not an object".to_string())?;
    let name = object
        .get("hook_event_name")
        .and_then(Value::as_str)
        .ok_or_else(|| "hook payload has no hook_event_name".to_string())?;
    if !CLAUDE_WORKER_HOOKS
        .iter()
        .any(|hook| hook.event_name == name)
    {
        return Err(format!("unknown hook event {name:?}"));
    }
    let text = |key: &str| {
        object
            .get(key)
            .and_then(Value::as_str)
            .map(bounded_text)
            .filter(|s| !s.is_empty())
    };
    Ok(IncomingSignal {
        event: to_snake_case(name),
        notification_type: text("notification_type"),
        message: text("message")
            .or_else(|| text("prompt"))
            .or_else(|| text("reason"))
            .unwrap_or_default(),
        claude_session_id: text("session_id"),
    })
}

/// Control characters removed, at most [`SIGNAL_MESSAGE_MAX_CHARS`] chars.
fn bounded_text(raw: &str) -> String {
    raw.chars()
        .filter(|c| !c.is_control())
        .take(SIGNAL_MESSAGE_MAX_CHARS)
        .collect()
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;
    use std::collections::BTreeSet;

    fn settings() -> TerminalHookSettings {
        TerminalHookSettings {
            bridge_bin: PathBuf::from("/bin/neige-codex-bridge"),
            base_url: "http://127.0.0.1:4040".into(),
            settings_dir: PathBuf::from("/data/terminal-hooks"),
        }
    }

    #[test]
    fn generated_env_is_exactly_the_declared_keys_and_the_bridge_contract() {
        let env = settings().env("card-1");
        let keys: BTreeSet<&str> = env.keys().map(String::as_str).collect();
        assert_eq!(
            keys,
            TERMINAL_HOOK_ENV_KEYS
                .iter()
                .copied()
                .collect::<BTreeSet<_>>()
        );
        assert_eq!(env["NEIGE_CARD_ID"], "card-1");
        assert_eq!(
            env["NEIGE_CLAUDE_SETTINGS"],
            "/data/terminal-hooks/card-1.json"
        );
        assert_eq!(env["NEIGE_HOOK_PROVIDER"], "claude");
        assert_eq!(env["NEIGE_CALM_BASE_URL"], "http://127.0.0.1:4040");
        assert_eq!(
            env["NEIGE_HOOK_URL"],
            "http://127.0.0.1:4040/internal/claude/hook?card_id=card-1"
        );
        let merged = settings().merge_env(
            &json!({"HTTP_PROXY":"p","NEIGE_CARD_ID":"forged"}),
            "card-1",
        );
        assert_eq!(merged["HTTP_PROXY"], "p");
        assert_eq!(merged["NEIGE_CARD_ID"], "card-1", "generated keys win");
    }

    #[test]
    fn terminal_settings_register_exactly_the_seven_events_with_table_matchers() {
        let json: Value = serde_json::from_str(&settings().settings_json("card-1")).unwrap();
        let registered: BTreeSet<String> =
            json["hooks"].as_object().unwrap().keys().cloned().collect();
        assert_eq!(
            registered,
            TERMINAL_HOOK_EVENTS.iter().map(|s| s.to_string()).collect()
        );
        assert!(
            json["hooks"]["PermissionRequest"][0]
                .get("matcher")
                .is_some()
        );
        assert!(json["hooks"]["Stop"][0].get("matcher").is_none());
        assert!(json["hooks"].get("PreToolUse").is_none());
        let command = json["hooks"]["Stop"][0]["hooks"][0]["command"]
            .as_str()
            .unwrap();
        assert!(command.contains("'/bin/neige-codex-bridge' --provider claude"));
        assert!(command.contains("NEIGE_CARD_ID='card-1'"));
        assert_eq!(
            TERMINAL_SIGNAL_EVENTS
                .iter()
                .map(|s| s.to_string())
                .collect::<BTreeSet<_>>(),
            TERMINAL_HOOK_EVENTS
                .iter()
                .map(|s| to_snake_case(s))
                .collect::<BTreeSet<_>>()
        );
        for event in DEFAULT_SIGNAL_EVENTS {
            assert!(TERMINAL_SIGNAL_EVENTS.contains(&event));
        }
    }

    #[test]
    fn parse_bounds_message_and_rejects_unknown_shapes() {
        let long = "x".repeat(400);
        let signal = parse_terminal_signal(&json!({
            "hook_event_name":"Notification","notification_type":"permission_prompt",
            "message":format!("needs\u{7}\n approval {long}"),"session_id":"s1"
        }))
        .unwrap();
        assert_eq!(signal.event, "notification");
        assert_eq!(
            signal.notification_type.as_deref(),
            Some("permission_prompt")
        );
        assert_eq!(signal.message.chars().count(), SIGNAL_MESSAGE_MAX_CHARS);
        assert!(signal.message.starts_with("needs approval x"));
        assert_eq!(signal.claude_session_id.as_deref(), Some("s1"));
        let prompt =
            parse_terminal_signal(&json!({"hook_event_name":"UserPromptSubmit","prompt":"hi"}))
                .unwrap();
        assert_eq!(prompt.event, "user_prompt_submit");
        assert_eq!(prompt.message, "hi");
        let end = parse_terminal_signal(
            &json!({"hook_event_name":"SessionEnd","reason":"prompt_input_exit"}),
        )
        .unwrap();
        assert_eq!(end.message, "prompt_input_exit");
        assert!(parse_terminal_signal(&json!([1])).is_err());
        assert!(parse_terminal_signal(&json!({"message":"no name"})).is_err());
        assert!(parse_terminal_signal(&json!({"hook_event_name":"NotAHook"})).is_err());
        assert!(parse_terminal_signal(&json!({"hook_event_name":7})).is_err());
    }

    #[test]
    fn remove_settings_file_only_touches_the_derived_path() {
        let dir = tempfile::tempdir().unwrap();
        let outside = dir.path().join("outside.json");
        std::fs::write(&outside, "x").unwrap();
        let inside = settings_path_in(dir.path(), "card-1");
        std::fs::write(&inside, "x").unwrap();
        remove_settings_file(dir.path(), "../outside");
        remove_settings_file(dir.path(), "");
        assert!(outside.exists());
        remove_settings_file(dir.path(), "card-1");
        assert!(!inside.exists());
        remove_settings_file(dir.path(), "card-1");
    }
}
